### ISSUE TITLE
Can't access console after running docker image

### ISSUE THREAD

**Issue by jayareddyd** [emitter-io/emitter#1]
![screen shot 2016-12-24 at 11 45 39 pm](https://cloud.githubusercontent.com/assets/5160033/21470219/a4d0108a-ca33-11e6-93a2-90535bb63645.png)
Hello,

I could able to build latest emitter locally for docker, but can't see the console or keygen in my browser accessing 127.0.0.1:8080/console, can you please let me know what's causing the issue.

**Comment by Kelindar** [comment]
There's a couple things to do here:
 1. Make sure the ports are bound to your host machine (eg: ´docker run -p 8080:8080´).
 2. The page should be ´/keygen' and not console.
