### ISSUE TITLE
MQTT client connection

### ISSUE THREAD

**Issue by jurgen-kluft** [emitter-io/emitter#101]
I have a question related to connecting to the emitter broker from for example an Arduino running a MQTT client (https://pubsubclient.knolleary.net/api.html).

Q: What do i fill in for the username and password ?

**Comment by Florimond** [comment]
Emitter doesn't use those parameters, you can set them to NULL. If the library you use requires you to fill them with something, you can fill them with whatever you want, those values will just be ignored by Emitter.
