### ISSUE TITLE
How many users can connect?

### ISSUE THREAD

**Issue by iranappo** [emitter-io/emitter#111]
Hi dear
I need your pack for programming chat app
I use MQTT protocol for Subscribe and Publish
My users are more than 1 million
There are two question :
1- Can i use your service instead mosquito ?
2- And if your answer is True,so can i use this service for java android?
Thanks

**Comment by Florimond** [comment]
Hello,

I assume you are referring to the cloud offer as advertised on the [Emitter.io](https://emitter.io/) website.
The load shouldn't be a problem. We will scale our cloud accordingly.

There is a [lib in Java](https://emitter.io/develop/java/) to help you talk to Emitter servers.
Clients communicate with Emitter servers using the MQTT protocol. You should be able to connect from Android using any MQTT library, following this short documentation : https://emitter.io/develop/creating-sdk/
