### ISSUE TITLE
Can I get channel_key through emitter.keygen() by secret_key ?

### ISSUE THREAD

**Issue by Aysnine** [emitter-io/emitter#112]
like this ?
```javascript
const emitter = require('emitter-io').connect({...});
let key = await emitter.keygen({
  key: secret,
  channel: 'summary/#/',
  type: 'rwls',
  ttl: 1200
});
```

**Comment by Florimond** [comment]
It seems correct. I assume you are following this documentation : https://emitter.io/develop/message-filtering/
Which contains an error since you need the secret key for the "key" parameter, but you didn't fall for it and use the secret key correctly.

**Comment by Aysnine** [comment]
Just want to create channel and channel_key by secret_key, like use `localhost:8080/keygen` page.
![image](https://user-images.githubusercontent.com/10137653/39768895-248b0186-531d-11e8-9efc-b1c050e4f0d9.png)
![image](https://user-images.githubusercontent.com/10137653/39769116-d72846b4-531d-11e8-8be5-984547836152.png)
What should I do? :)

**Comment by Aysnine** [comment]
My bad description, I had the secret key, but only to get channel_key through keygen page. I need other ways.

I read the here, think like:
![image](https://user-images.githubusercontent.com/10137653/39788315-785113ca-535c-11e8-8dde-d7a5927d227e.png)

Channel_key comes from secret_key?
What the emitter.keygen() doing?
What does emitter.keygen() return?
Can I get channel_key through emitter.keygen() by secret_key？

**Comment by Aysnine** [comment]
Thanks, I got it by this code:
```javascript
const emitter = Emitter.connect({ ... });
const secret = 'v3yIpR5BnziLp5Mlwv5G5pwQsrGhJJ0g';

emitter.on('connect', () => {
  emitter.keygen({
    key: secret,
    channel: "chat/#/",
    type: "rwls",
    ttl: 86400 // one day
  });
});

emitter.on('keygen', (esponse => {
  console.log('keygen result: ', response);
});

/*
keygen result:  { status: 200,
  key: '87ZDxYKzx9q0oTRExILxg-OEdbBZ9XEA',
  channel: 'chat/#/' }
*/
```

So, read the official doc and javascript SDK code, maybe two event descriptions are missing:

![_q6wmmhwnj 8 fm9r0r8g](https://user-images.githubusercontent.com/10137653/39791137-91830c1c-536c-11e8-9fdd-da2c99616e5e.png)

![image](https://user-images.githubusercontent.com/10137653/39791191-e6288fd0-536c-11e8-8438-af9be0b4c317.png)

An official document would be even better :)

**Comment by geekguy** [comment]
Thanks, @Aysnine. 

I agree it should be there in the official document (unless there is another api).
