### ISSUE TITLE
The client don't be informed if  the security key is invalid

### ISSUE THREAD

**Issue by mshafiee** [emitter-io/emitter#113]
There is no error handling in:

https://github.com/emitter-io/emitter/blob/5878cce20b9a30facbd1a196e801a668fccd1bec/broker/conn.go#L172

So the client don't be informed if  the security key is invalid.

**Comment by richterk** [comment]
There is already an error handler.  Why not push all errors to be handled by a handler consumers will already be binding? https://github.com/emitter-io/javascript/blob/master/lib/emitter.ts line 265 to 276.  This would be intuitive from a developer's perspective, and could be called like you said from an MQTT event posting to emitter/error/ or something.

**Comment by Kelindar** [comment]
@mshafiee @richterk  Here's a proposal to address this issue on the broker: https://github.com/emitter-io/emitter/pull/164
