### ISSUE TITLE
schedule a message ?

### ISSUE THREAD

**Issue by mshanak** [emitter-io/emitter#12]
hello
can i schedule a message to be developed at specific time in the future ?

regards

**Comment by Florimond** [comment]
Hi,
not on the emitter side no. What's your use case?

**Comment by mshanak** [comment]
i need  a message to be sent to the subscribers (apps) at 12:00PM , but the sender will send the message any time before that time .

**Comment by Florimond** [comment]
You cannot have the subscriber receive the message before that time, but only process it (show it to the user, or whatever you have to do with it) at a specific time?

**Comment by VladimirAkopyan** [comment]
This strikes me as something that isn't inherently be part of the messaging system. 
This appears to be something that should be part of your server-side functionality.

**Comment by dawsontoth** [comment]
I agree -- there's lots of ways to implement this, depending on the use case:

1. Send the message right away, and on the client, surface it to the user at the appropriate time.
2. Wait to send the message until the appropriate time, using server-side functionality.
3. Add a man-in-the-middle that listens for a delayedMessage from the sender, waits until the appropriate time, and then sends theMessage at the appropriate time to the consumer.

**Comment by Kelindar** [comment]
Agreed, there's plenty of ways of implementing this already. Closing this issue.
