### ISSUE TITLE
Link to Presence in Wiki is Incorrect

### ISSUE THREAD

**Issue by dawsontoth** [emitter-io/emitter#13]
If I knew how to fork and submit a PR for the Wiki I would, but it's not immediately apparent to me, so I'll just create an issue instead...

Super minor, but the link to the Presence Wiki page is broken in the Getting Started page.

Here's the steps to fix:

1. Go to https://github.com/emitter-io/emitter/wiki/1.-Getting-Started
2. Search for "Presence" and find the link. It's presently resolving to https://github.com/develop/presence
3. It should link instead to https://github.com/emitter-io/emitter/wiki/4.-Presence I believe the relative link could be `4.-Presence`, thus this markdown: `See [presence](4.-Presence) for more details.`

https://stackoverflow.com/questions/6474045/linking-to-other-wiki-pages-on-github

**Comment by Florimond** [comment]
Thank you, I fixed it.

You should see two buttons, "Edit" and "New issue", just on the right  of the main title of the page.

**Comment by dawsontoth** [comment]
Hmm, I don't see those buttons when I'm on the wiki here. If I look at one of my own repos, I see them. And I don't see any settings in my repo to enable or disable collaboration. Mysterious. Closing this issue as you've taken care of it, and I've verified. Thanks!

**Comment by Florimond** [comment]
Actually, I hadn't thought this through. This wiki is used as the source of emitter.io's content. So the previous link was resolving to the right address in emitter.io's context. I've restored the previous link.
