### ISSUE TITLE
HA and DR

### ISSUE THREAD

**Issue by gedw99** [emitter-io/emitter#132]
I don't see anything in the docs about high availability or disaster recovery.

Sure I can dig through the code and work it out myself but it's not great.

For example does your cluster support being partitioned and then catchup when partition dies.
Does your client support redirect when one server becomes partitioned for whatever er reason. By partitioned I mean network partitioned in the above questions.

Thanks for this great project !!

**Comment by Kelindar** [comment]
Yeah, documentation still needs a lot of work. Feel free to contribute though.

On the HA & DR: emitter is designed as an **AP** (available & partition tolerant) system, so in case of a network partition the broker will be still available, but the messages will not be routed to the unreachable partition. When the network recovers, gossip protocol will re-sync and merge the partitioned state and messages will start to be routed.

**Comment by gedw99** [comment]
Thanks for that. Ok all good.

Regarding the store. Where is it in the code ? I saw and in memory one in the providers namespace... ? Missing something ?

I can help contribute.
My main reason is because I need the functionality you provide but I also need an orchestration / event store for a semi CQRS style system. 
I reckon is ok to use Mqtt for my inner communications as well as clients to servers.  From what I can see some of the intrinsic aspects are there.

If you have had any thought along the way for using emitter as a event sourcing / cqrs system it would be awesome to hear them.

I like the new stats golang / gopherjs with the custom bi ary serialisation. Looking forward to benching it.

**Comment by Kelindar** [comment]
Right now, only in memory store is available but disk-backed one is coming (https://github.com/emitter-io/emitter/pull/133). I hope to land this PR over this weekend and have replication and stuff done in a week or two.

**Comment by gedw99** [comment]
super.. will take a look. I shall close this, and raise more fine issues as i hit things.. 

thanks again..
