### ISSUE TITLE
.net core 2.0 Migration

### ISSUE THREAD

**Issue by sandeeprachamalla89** [emitter-io/emitter#14]
Team,
Recently Microsoft announced the latest version of .net core 2.0 on August 14th,2017. Currently my project is built upon .net core 1.1 and .netstandard 1.5. When I looked into emitter.server & emitter.runtime they both are under the v1.1 and standard 1.5 respectively. If I try to change the target framework to .netstandard2.0 & .netcore2.0 , emitter is getting failed with lots of errors related to dll references. 

So, can i have a update from your team, Like Is there any plan to migrate your code src to latest .netcore 2.0? and when can we all expect these changes. Any ETA is appreciated.

**Comment by Kelindar** [comment]
Hi @sandeeprachamalla89, no plans for .net core 2.0 yet, but we'll have a look.

**Comment by Florimond** [comment]
Hi @sandeeprachamalla89 ,

I'm afraid it's a bit early for Emitter to adopt core 2.0. But you can expect some updates in a couple a months.

**Comment by Kelindar** [comment]
Closing this as we've migrated the master to `go`.
