### ISSUE TITLE
Using Multi-Stage build for Docker Images

### ISSUE THREAD

**Issue by dtchanpura** [emitter-io/emitter#145]
There can be significant decrease in Docker Image size using Multi Stage Builds

```Dockerfile
FROM golang:alpine AS builder
....
# install build time dependencies
....
RUN go install
# above command will save an executable binary /go/bin/emitter

FROM alpine:latest
COPY --from=builder /go/bin/emitter .
EXPOSE ...
CMD ['./emitter']
```
Reference: https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds
Supported after Docker 17.05

**Comment by Kelindar** [comment]
Looks good, will port our docker image to that. Thanks!

**Comment by dtchanpura** [comment]
I have added it in the fork (https://github.com/dtchanpura/emitter). Let me know if I create a pull request and close this.
