### ISSUE TITLE
Message size limit

### ISSUE THREAD

**Issue by ljesparis** [emitter-io/emitter#146]
what is the max size of the message?
can i send 4mb size or more?

**Comment by Kelindar** [comment]
The max in the broker should be 64K. We recommend using emitter to send small messages around (as a message broker as opposed to a data broker).

You could either use Kafka or emitter with messages containing S3 urls (so upload, download on S3 is the clients).

**Comment by Kelindar** [comment]
This being said, you can try adjusting max message size on emitter and benchmark for yourself.
