### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by VladimirAkopyan** [emitter-io/emitter#15]
I love the project - I considered using it in one of our project, but we ended up going with Kafka instead. 
The main obstacle in adopting this in a serious LoB application is understanding for where you are headed, and what are your plans for the project. 
That is also quite vital when it comes to contributing to the project - can't work on anything beyond simple bug fixes. 

@Kelindar mentioned that you guys are planning to rebuild emitter in Golang, it would be good to understand what that might look like, will that replace or be supported side by side with c#, etc..

**Comment by Kelindar** [comment]
This is a very good point, I'll lay the roadmap on paper along with the contributing agreement.

The (initial) golang version is complete in terms of features and has a compatible API. We're going to roll it out in coming month or two - see 'nextgen' branch.

Main focus right now is to bring emitter to a production ready state and make sure it can withstand any network partition and scales well. Hence the golang migration, we wanted to take advantage of extensive distributed systems libraries available in Go, ARM and native code. This will be the only maintained version, we will be dropping our C# version and focusing on Go.

**Comment by sandeeprachamalla89** [comment]
So as you mentioned of dropping C# version, does that mean like you going to remove "Emitter" nuget package as well?? or it will stay as ease without any updates? could you please confirm on this.

**Comment by Florimond** [comment]
@sandeeprachamalla89 
What has now been stopped is the development of the Emitter core platform in C#. However, the nugget package you are referring to is just a lib used to develop client applications that can interact with the Emitter API. This API hasn't changed when re-implementing the core platform in Go, and I see no reason to stop providing a C# SDK. On the contrary, we are looking to expand the list of languages we provide an SDK for.

**Comment by VladimirAkopyan** [comment]
It would be great to hear your thoughts on building a distributed system with Go vs .Net, and the difficulties you've encountered. 
I know nothing about distributed computing, but I presume things like Orleans and Akka weren;t good enough?

**Comment by deiu** [comment]
Hi! Is there any news on this topic? We'd love to see an (updated) roadmap for 2018.

**Comment by Kelindar** [comment]
Will do. Generally speaking we want to focus on several areas: 
1. stability and more extensive test coverage 
2. improving channel keys to add the ability to restrict a specific key
3. more options for message storage (redis streams for example)
4. support for QoS 1 (at most once)
