### ISSUE TITLE
Question: are clients just pure mqtt clients

### ISSUE THREAD

**Issue by gedw99** [emitter-io/emitter#152]
Curious as to how difficult it is to write a dart client ?
Are clients only standard mqtt clients ?
I imagine they would need to ACK back to the message broker.

Also what about ordering of messages.
Are Lamport clocks used on the clients to allow offline editting with Operational Transforms ?

**Comment by Kelindar** [comment]
It's relatively straightforward to write a client as emitter is using MQTT protocol. Here some docs that might help: https://emitter.io/develop/creating-sdk/

Messages are just binary blocks, and we don't guarantee any global ordering. For storage, however, each message gets a time-sortable uuid. This would still require some clusrtr-level clock synchronisation.

**Comment by gedw99** [comment]
Ok makes sense.

Will check the link.

About cluster and clocks. There is no guarantee of ordering I presume. Will
you ever do it.
Minio btw does it using a cluster clock to give absolute ordering. Ever
transaction must get it's next sequence from the global clock.
