### ISSUE TITLE
Using emitter in a docker-compose environment?

### ISSUE THREAD

**Issue by Nefiron** [emitter-io/emitter#155]
Hey!

I am struggling with using the emitter/server image in a docker-compose environment.

First of all it dosent seem to recognize my conf.yml as it won't volume the disc.

Also the license won't be recognized in the EMITTER_LICENSE if i put it under Environment in the docker-compose.yml.
What would be the right approach in a situation like this?

**Comment by Kelindar** [comment]
It should work with environment variables in compose, have you checked the documentation? https://docs.docker.com/compose/environment-variables/
