### ISSUE TITLE
Is it possible to fast forward messages? 

### ISSUE THREAD

**Issue by guijun** [emitter-io/emitter#156]
e.g. We want to skip  1000 messages before OnMessage

**Comment by Florimond** [comment]
I'm not sure I understand. Do you mean you want to subscribe but ignore the first 1000 messages?

**Comment by guijun** [comment]
Yes, exactly.

**Comment by guijun** [comment]
Yes, exactly. 
If we can ignore messages before a timestamp should be cool.
e.g.
Publisher has published 10000 messages.
Subscriber receive 1000 message then go offline.
Subscriber can resume at a given timestamp or index or something.

**Comment by guijun** [comment]
If publisher pub 100 messages with TTL.
subscriber will receive 100 messages each time when it connect to broker.

if subscriber didn't connect to broker, the subscriber will miss messages.
