### ISSUE TITLE
about distributed deployment

### ISSUE THREAD

**Issue by zhushouqin** [emitter-io/emitter#158]
Hi，guys
there is a issue : we use 25000 equipment do stress testing，two linux machine, IP is 10.18.218.71 and 10.18.218.72 .  4 cpu,  32G memory.
test:  1. operation system subscribe 10.18.218.71 , and 25000 equipment connect 、subscribe、publish is ok. 
2. another real equipment connect and subscribe 10.18.218.72, notify data failed. 
3. if 20000 equipment test is ok .

question: 1. if cluster data synchronous have some bugs？
2. or the memory limit the connect number? 
3. if mqtt cluster need lead-in MQ？

**Comment by Kelindar** [comment]
I'm not sure I understand the problem, do you have an example?
