### ISSUE TITLE
Publish and Presence over HTTP

### ISSUE THREAD

**Issue by kelindar** [emitter-io/emitter#16]
Right now, publishing of new messages requires the SDK which could be *not-very-convenient* when integrating with a website. For example, if one wants to track page views or connected users it would be easier to simply support `Publish Over HTTP`.

Similarly, we need to investigate getting the `Presence over HTTP` (just the `status`). Alongside, we should investigate the possibility and performance implications of `Subscribe over HTTP`.

**Comment by gedw99** [comment]
You can take the ho client and use gopherjs to compile it to JavaScript or WASM.
Even very complex libraries work with only tiny build tag changes I have noticed.

Worth a try because then you have a single source - the golang client code.
