### ISSUE TITLE
Add channel key management

### ISSUE THREAD

**Issue by flokX** [emitter-io/emitter#162]
This feature request is primary for the official webpage but I don't know where is a better place for it.

Currently it is only possible to create new channel keys with the cloud console. The problem is that there is no control of all active keys or no quick possibility to find out which access rules belong to one channel.

It would be a pleasure, to have an overview of all channel keys and their access rules and the option to delete specific keys. Anyone who already thought the same?

**Comment by Kelindar** [comment]
This can be done, but I wouln't want to store keys on our end as if our web UI gets hacked the keys would get compromised. We could store hashes of keys instead and show something like `ABC********** (SHA-1:XXXX)`

**Comment by flokX** [comment]
Jeah, that's a good safety principle. Maybe it was a little bit unclear, but I think the most important thing is to display the channel names.
Then it's the developers part to manage his keys, and they can't become compromised. Nevertheless the developer can manage the channels via he web interface.

**Comment by gedw99** [comment]
Currently ou gen a hash key for all operations on a Namespace currently.
We need a way to map User & Roles to those hash keys perhaps ?
