### ISSUE TITLE
Occasional slow responses... Emitter cloud

### ISSUE THREAD

**Issue by richterk** [emitter-io/emitter#165]
I’m hoping that I’m posting this to the right place.

So, I’m curious if anyone has any thoughts, or has experienced any slowness on the response times from Emitter Cloud. I love this project, and want to use it, but I’m seeing delays of up to 10 seconds on some responses from the broker. Not good for a platform whose whole premise is speed and low latency.

A little info: 

I’m building on nodejs, using typescript. It’s a lightweight executable. The only added library (right now) is the MongoDB driver. It’s a server implementation for a player info and auth service that interacts with connected players for my company’s game products.

**Comment by Kelindar** [comment]
Thanks for your kind words. It's unlikely to be emitter-broker issue tho, more likely our cloud infrastructure. 

We'll need to test this and we're building separately a benchmarking and latency analysis tool for emitter so we can hopefully diagnose some of these issues.
