### ISSUE TITLE
LWWSet Garbage Collection

### ISSUE THREAD

**Issue by Kelindar** [emitter-io/emitter#17]
Currently, our [last-write-wins set](https://github.com/emitter-io/emitter/blob/master/collection/lwwset.go) CRDT does not have garbage collection integrated. This is required to minimise the size of gossip transfers as without it it will tend to snowball over time.

![](http://blog.licenser.net/images/posts/2013-06-11-asyncronous-garbage-collection-with-crdts2.png)

More information: [Async GC with CRDTs](http://blog.licenser.net/blog/2013/06/11/asyncronous-garbage-collection-with-crdts/), [CRDT Notes](https://github.com/pfrazee/crdt_notes)

**Comment by gedw99** [comment]
AH i was wondering how the whole system handled the aspects of consistency.

There is some great work going on with the Garbage Collection issues of CRDT.


https://github.com/trvedata
- Martins CRDT project !!!
	- https://github.com/automerge/automerge
		- The CRDT working project.
		- Ouputs from it are immutable so it works with React with zero changes
		- ReadMe has linsk to all the projects
	- https://github.com/ept
		- his personal github

**Comment by Kelindar** [comment]
This is interesting, thanks for the extra pointers @gedw99. We'll have to address this issue soon, it's long overdue that we integrate garbage collection in our LWWSet.

**Comment by gedw99** [comment]
CRDT is really hard. I was surprised you even had LWWSet - Hats off to your
forethought !!!. Most of these types of architectural message bus style
systems dont even have it. Its like no one ever thinks you might have to
handle network partitions...
