### ISSUE TITLE
IAAS management using Istio

### ISSUE THREAD

**Issue by gedw99** [emitter-io/emitter#178]
I was thinking about how best to run the stack on own cloud.

If you want to bring up your own cluster you need an IAAS layer.
With K8, Istio is the supported way now.

The shows how to get Weave working this way.
https://github.com/weaveworks-experiments/istio-demo 

The One avantage is that the all monitoring, logging, auth can be controlled outside of the emitter cloud.

**Comment by Kelindar** [comment]
Here's an example with DigitalOcean: https://github.com/emitter-io/emitter/tree/master/deploy/k8s/digitalocean, I don't have much experience with Istio, will give it a shot.

**Comment by gedw99** [comment]
hey @Kelindar thats awesome !
Will be easy to add a IAAS gateway in front that acts as a proxy. 
I have sort of gone off istio. Too complex. Plenty of others out there these days.

this one is very simple:
https://github.com/alash3al/httpsify

Its using this, which has all the extra bits needed:
https://github.com/vulcand/vulcand

And then Matt's new SSL magic :)
github\.com/mholt/certmagic
