### ISSUE TITLE
Subscriptions are not returning with the prepended user key preventing Node-Red from receiving response

### ISSUE THREAD

**Issue by ecolasanto** [emitter-io/emitter#181]
I raised an issue with Node-Red not being able to receive subscriptions from api.emitter.io server.
In the response to the Node-Red issue (e.g. Cannot Subscribe to MQTT topic on api.emitter.io server #2018) it appears that the emitter server does not respond with the user key prepended so Node Red cannot associated the response to any node in the Node Red system, hence it gets dropped.
Can the emitter service be altered to also return the user key with the topic?
I hope so..Thanks.

**Comment by Kelindar** [comment]
I'm not very familiar with Node-Red. @Florimond had a look at this earlier tho.

**Comment by ecolasanto** [comment]
If you read the following forum thread you will see the issue as I described it to the node-red forum, and the reply from one of the originators of node-red.
Thanks,--Eric
    On Saturday, January 5, 2019, 7:36:36 PM EST, Roman Atachiants <notifications@github.com> wrote:  
 
 
I'm not very familiar with Node-Red. @Florimond had a look at this earlier tho.
