### ISSUE TITLE
Add message storage replication

### ISSUE THREAD

**Issue by gedw99** [emitter-io/emitter#182]
From what i can see the durable storgae is not replicated.
Raft looks to be the cleanest approach these days with badger.

There is a new raft implementation that looks very high quality and also easy to use.
https://github.com/lni/dragonboat

Not everyone wants this of course, but i would be good to add for those that do as an option perhaps.

**Comment by Kelindar** [comment]
Emitter is actually HA but designed to be **A**vailable and **P**artition Tolerant (as in CAP theorem). So by introducing a consensus algorithm such as raft to replicate message storage this would make it unavalable during network partititions. On the bright side, there's alternatives to consensus so we are likely to implement some sort of message replication in future.

This being said, this is not a priority as currently we actually delegate message storage durability to kubernetes. With a kubernetes deployment, persistent volumes are actually separate - so if one broker goes down, the persistent volume will get automatically reattached to a new broker. Thus, messages are not lost and most of cloud provides (eg. AWS, Azure, GCP) do provide reliable and replicated volumes. For example, in AWS case, kubernetes would use EBS volumes.

> Each Amazon EBS volume is automatically replicated within its Availability Zone to protect you from component failure, offering high availability and durability.
https://aws.amazon.com/ebs/

**Comment by gedw99** [comment]
thanks @Kelindar Pretty cool using k8 backing technique. Always wondered how well that worked.

Maybe then a simple message replication for V1 of replication to a WARM ?

this is what i use for NATS for example:
https://github.com/octu0/nats-relay

**Comment by Kelindar** [comment]
Thanks @gedw99 ! We will for sure add message replication at some point in future, but also more storage providers. Few I'd particulary want are Kafka & S3 where you could asynchronously append messages onto and use it for recovery as you said.
