### ISSUE TITLE
Getting Error when "go get"ing Emitter

### ISSUE THREAD

**Issue by dawsontoth** [emitter-io/emitter#19]
On Mac 10.12.6:

```bash
> rm -Rf ~/go
> go version
go version go1.9 darwin/amd64
> go get github.com/emitter-io/emitter && emitter
# github.com/emitter-io/emitter
ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in type..eqfunc.[106]string from /var/folders/gb/bn5tvy2s2vqcf6hxs9qz17tm0000gn/T/go-link-417292192/go.o. To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
-bash: emitter: command not found
> 
```

What are the supported platforms for this new pivot of the implementation? What versions of Go?

**Comment by Kelindar** [comment]
I think your `GOPATH` `bin` folder might not be in the path. It should work.

We'll be supporting every platform supported by go 1.9, not doing any magic there. In fact, we had emitter running on the first model of raspberry pi with ARM cpu, and we tested on Linux/Win/MacOS as well.

**Comment by dawsontoth** [comment]
Oh man, you're totally right. My bad! Should have figured that out on my own, thanks.
