### ISSUE TITLE
QueryManager.Send might be infinity blocked

### ISSUE THREAD

**Issue by mingmingtsao** [emitter-io/emitter#191]
Hi, I found that if a related "`response`" peer message was received after `queryAwaiter.Gather` has reached its time out, the QueryManager will be blocked on the method "[`onResponse`](https://github.com/emitter-io/emitter/blob/6f36cb9792eda0e8109a31ff9111315c1ae13e06/internal/broker/query.go#L107)".

**Comment by Kelindar** [comment]
Merged the PR, but this looks like it could only happen under 2 conditions:

1. `Gather` has reached a timeout.
2. `defer func() { a.manager.awaiters.Delete(a.id) }()` didn't execute yet.

We should probably also consider marking a `receive` channel as `nil` and adding a check for the nil channel during `onResponse`.
