### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by dyanakiev** [emitter-io/emitter#194]
Hello,
I get connection pending in the client in network tab its tryting to connect to wss://ws1.xx.bg:8943
I have not generated any ssl's because it says that autocert is used am i right?

Below is the client and server configuration:

Client:
```
var client = emitter.connect({ host: 'ws1.xx.bg',port: 8943 }); 
```

emitter.conf:
```
{
        "listen": "ws1.xx.bg:8983",
        "license": "xx",
        "tls": {
                "listen": "ws1.xx.bg:8943",
                "host": "ws1.xx.bg",
                "email": "d@xx.bg"
        },
        "storage": {
                "provider": "ssd"
        }
}
```

**Comment by Kelindar** [comment]
Autocert should be used yes, but it would need to reach the hostname on the port `80` in order to validate this. This is due to a recent change as SNI verification was deprecated.
