### ISSUE TITLE
How to emulate request/response pattern (or RPC) on emitter?

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#197]
Some brokers like Kafka or RabbitMQ has built-in support for request/response pattern or remote procedure calls (RPC). 

Do you have a working example of implementing this pattern on emitter?

Thanks :)

**Comment by Kelindar** [comment]
Have a look at this demo: https://github.com/Kelindar/emitter-client-server

**Comment by postacik** [comment]
Thanks. I'll have a look and come back if any questions arise. :)

**Comment by postacik** [comment]
I tried the sample application.

Are the following two samples equal in terms of functionality?

```
client.CreatePrivateLink(channelKey, "demo/", "s", onMessageReceived)
client.PublishWithLink("s", text)

```
```
const privateLink = "demo/" + randomString
client.Subscribe(key, "demo/", onMessageReceived)
client.Publish(channelKey, privateLink, text)

```

**Comment by Kelindar** [comment]
These two are similar, but not equivalent - the private link would also create a "dedicated key" for the sub-channel thus ensuring that only the client who created the link can publish to it.

The Go client is synchronous, it does the "await" in the SDK.

**Comment by postacik** [comment]
But in your sample the server can publish a reply to the private link. I don't really get it. :(

```
func onMessage(c *emitter.Client, msg emitter.Message) {
	response := strings.ToUpper(string(msg.Payload()))
	c.Publish(key, msg.Topic(), response, emitter.WithoutEcho())
}
```

**Comment by Kelindar** [comment]
Right, the server actually has a pre-generated key which can publish to all sub-channels. This gives the server more permissions than to its clients.

**Comment by postacik** [comment]
Everything in this project is super easy to understand and implement when compared to other brokers but I really  could not understand this CreatePrivateLink and PublishWithLink feature.

I also watched your Youtube video (https://www.youtube.com/watch?v=_FgKiUlEb_s) but no way.

Maybe I should watch again, read again and go deeper in your source code.

Anyway, thanks for your help. :)

**Comment by postacik** [comment]
It became more clear with your latest video:

https://www.youtube.com/watch?v=SHPkJ6ESnpw

I'm making an analogy with my previous client/server implementations:

The channel name corresponds to the request/response channel. For example "v1/requests/"

I can send user related requests to this link with payloads like the following:

```
{ "commandName": "loginUser", "userId": "kevin", "password": "spacey" }
{ "commandName": "addUser", "userName": "Kevin Spacey", "userId": "kevin", "password": "spacey" }
{ "commandName": "getUsers", "filter": "*" }

```
And the private link id (the last segment of the message topic) is the client id. So the server can use it like an authentication cookie in a web application to serve subsequent requests after login.

My last question (I hope) :

Are CreatePrivateLink and PublishWithLink functions and emitter.WithoutEcho() option supported in the Javascript and C# SDK?

If not, can you give a hint on how to add them?

**Comment by Florimond** [comment]
It's not in the JavaScript or C# SDK yet, but it's been added to the Python SDK. Maybe you can have a look at the code here: https://github.com/emitter-io/python

**Comment by Florimond** [comment]
@postacik I've just added Link, and PublishWithLink to the Javascript SDK. I'm busy updating the documentation. To create a private link, it's a parameter of Link.

Hope it helps.

**Comment by postacik** [comment]
Thank you very much :blush:
