### ISSUE TITLE
Storage alternatives?

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#198]
As far as I can see from the documents, there are only 2 storage alternatives: inmemory and ssd.

The only config option for ssd I could find is the dir option to specify the location of the file.

Are there any other options for ssd storage and any other alternatives for storage?

**Comment by Kelindar** [comment]
Currently only these 2 indeed, with limited options exposed. You can browse the code here: https://github.com/emitter-io/emitter/tree/master/internal/provider/storage

**Comment by postacik** [comment]
Thanks
