### ISSUE TITLE
about cluster

### ISSUE THREAD

**Issue by sunface-io** [emitter-io/emitter#20]
Hi all: 
    I have two questions about cluster here:

    A Cluster has two nodes: A、B
    1. If User X connected to A, Y connected to B, how does X and Y communicate?
    2.If node C join the cluster, how does you migrate the persistent data for the hash

**Comment by Kelindar** [comment]
1. The cluster uses Gossip+CRDT to maintain a state of all subscriptions, if a user X sends a message to A and both X and Y share the same subscription, the message will be forwarded within the cluster to B and in turn to Y, emitter is designed to work this way.
2. Emitter is not a database, so it does not migrate or maintain any persistent data at the moment.

**Comment by sunface-io** [comment]
thanks for reply,by the way ,emitter is really great!
