### ISSUE TITLE
Could not debug emitter in IDEA: could not launch process: decoding dwarf section info at offset 0x0: too short

### ISSUE THREAD

**Issue by guijun** [emitter-io/emitter#203]
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/kin/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/79/ng_nwpm54xv0t66tc404jd040000gn/T/___emitter -gcflags "all=-N -l" github.com/emitter-io/emitter #gosetup
/Applications/GoLand.app/Contents/plugins/go/lib/dlv/mac/dlv --listen=localhost:54394 --headless=true --api-version=2 --backend=default exec /private/var/folders/79/ng_nwpm54xv0t66tc404jd040000gn/T/___emitter -- #gosetup
API server listening at: 127.0.0.1:54394
could not launch process: decoding dwarf section info at offset 0x0: too short

**Comment by kelindar** [comment]
This is likely an issue with delve, not emitter (see https://github.com/go-delve/delve)

**Comment by Florimond** [comment]
A workaround, although not ideal, is to downgrade to go 1.9.4.

**Comment by guijun** [comment]
thanks for feedback.
but ,I'm wondering why the issue doesn't exist when I debuging other apps, :-(
btw:
go version
go version go1.11.5 darwin/amd64

**Comment by guijun** [comment]
The issue doesn't exist if I remove import 	"github.com/emitter-io/emitter/internal/broker".

**Comment by guijun** [comment]
issue gone after upgrade to go 1.12
