### ISSUE TITLE
The LookUp function which in Trie.go file has performance problems in 1:N pattern if the value of N is too large

### ISSUE THREAD

**Issue by shuzf** [emitter-io/emitter#204]

**Comment by Florimond** [comment]
Can you explain why, with an example? Do you have maybe a benchmark?

**Comment by shuzf** [comment]
When the value of N is too large, the function trie.Lookup calls AddUnique will generate a for{for{}} loop operation, the worst case will execute 1+2+3+..+N = (1+N)*N/2 times,the time complexity is O(N2). the benchmark finds that with the increase of N, the Lookup reaches the ms level or even higher.

**Comment by kelindar** [comment]
https://github.com/emitter-io/emitter/pull/206

**Comment by kelindar** [comment]
This should do it, @shuzf could you test? Reopen this issue if the problem persits.
