### ISSUE TITLE
conn.Send is called in server but client recv nothing

### ISSUE THREAD

**Issue by guijun** [emitter-io/emitter#205]
go func(){
		mqeMaster :=emitter.NewClient(emitter.WithPingTimeout(time.Second),
			emitter.WithKeepAlive(time.Minute),
			emitter.WithMaxReconnectInterval(time.Second),
			emitter.WithConnectTimeout(time.Second),
			emitter.WithAutoReconnect(true),
			//		emitter.WithBrokers("tcp://127.0.0.1:8080"));
			emitter.WithBrokers("tcp://localhost:8081"));

		err:= mqeMaster.Connect()
		if err!=nil {
			fmt.Printf("Emitter Master Error %s\n",err)
		} else {
			fmt.Printf("Emitter Master Connected\n")
		}

		mqeSlave :=emitter.NewClient(emitter.WithPingTimeout(time.Second),
			emitter.WithKeepAlive(time.Minute),
			emitter.WithMaxReconnectInterval(time.Second),
			emitter.WithConnectTimeout(time.Second),
			emitter.WithAutoReconnect(true),
			//		emitter.WithBrokers("tcp://127.0.0.1:8080"));
			emitter.WithBrokers("tcp://localhost:8081"));

		err= mqeSlave.Connect()
		mqeSlave.Subscribe("B8Ar-1G0YGyjUEJB50GfdBYgITgX9CPI","match/demo",func(client *emitter.Client, msg emitter.Message) {
			pl:=msg.Payload();
			fmt.Printf("Recv %s %s %s\n",string(msg.Topic()),string(msg.Payload()), string(pl))
		});
		for i :=1;i<1000;i++ {
			mqeMaster.Publish("w44ornEqgjZ-yNiEKG9D4TJmwtnhhcFG","match/demo","Demo Msg");
		time.Sleep(time.Second)
		}
	}()

**Comment by Florimond** [comment]
It was a problem with the go SDK. It's fixed now and your code should work.
