### ISSUE TITLE
Password authentication for MQTT

### ISSUE THREAD

**Issue by satishThakur** [emitter-io/emitter#209]
I do understand emitter has key based authentication and authorization which is more secure and better way of handling authentication.

But I have devices in production which connect to MQTT broker via username, password. I want to move MQTT broker to Emitter but issue is I have no way to upgrade all the remove devices for channel name.

So I was thinking of adding support for mapping username, password to a generated key - which can be configured in config file.
If this config is provided emitter would authenticate at the time of connection and bind that connection to the fixed key. For all the publish and subscribe call on that connection it would prepend key with the topic names.
Not sure if this is generic feature or it can be made generic so that it can help others as well. Please let me know your opinion on the same.

**Comment by robotamer** [comment]
I would also appreciate a solution to the key security. Making it optional would be great.

1) I use MQTT totally offline on a sail boat, and have no access to creating keys. I have created some keys on a laptop with the same settings. But frankly, I don't need security at all.

2) There are many Android apps that connect to MQTT to display charts etc. But I have not found a single one that supports keys for security.
