### ISSUE TITLE
Puback is ignored

### ISSUE THREAD

**Issue by sunface** [emitter-io/emitter#21]
Hi all: 
     Why does emitter ignore puback packet?
     If puback is not handled, the message will not be deleted. Maybe when a user get online, will he get all the messages which are not expired?

**Comment by Kelindar** [comment]
Currently, we only support QoS 0 (at most once delivery), hence the ignore of puback. We're going to add support for QoS 1 (at least once) going forward, and we will integrate our message storage with it as well.

**Comment by sch00lb0y** [comment]
@Kelindar I would really like to work on this. retry based on puback is enough? I have one more doubt that if the network goes down socket will be lost right? In that scenario, how to do the retry. (I may be wrong). I already made some work in my local repo. If you can clear the doubt, I can send PR straight away now :smile:
