### ISSUE TITLE
Presence question

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#210]
Hi,

If I subscribe to "channel/" for presence changes, I get presence events for subchannels (e.g. channel/sub), too.

Is this the normal behavior?

**Comment by Florimond** [comment]
Yes, this is the intended behavior.

**Comment by postacik** [comment]
Another question:

When I get a presence event for a channel, it only sends me the ID of a subscribed or unsubscribed user.

But what I need is the number of users subscribed to that channel.

Do I have to calculate and keep the number of subscribers from these events or is there way to get the number of subscribers?

**Comment by Florimond** [comment]
Yes. There used to be an "occupancy" field, in the C# version of Emitter, long ago. But if I remember correctly this field was difficult to maintain, and we decided we'd rather have the client maintaining this value if needed than risking confusion.

So the way to go is to request a presence status, count the results, and then update this count when events arrive.

**Comment by postacik** [comment]
Suppose I subscribe to presence of channel "server/" using "status = false, change = true".

When I get a subscribe event for channel "server/device1", can I get the subscriber list for device1 using "channel=server/device1, status = true, change = false"?

Would that have any effect on emitter performance?

**Comment by postacik** [comment]
And where can I find C# version of emitter?

**Comment by Florimond** [comment]
Yes, it's more expensive to gather each time the list of all subscribers on the cluster side. Whether it's a viable option depends on your use case.

The C# version is no longer available.

**Comment by postacik** [comment]
Thanks :)

Is it possible to download the C# version from an archive?

**Comment by Florimond** [comment]
The C# version was on the same repo. It was reinitialized to host the go version with [this commit](https://github.com/emitter-io/emitter/commit/57dd63121157e0077776fee86ab2902b2b641603).
Anything before that is the old C# version. But I'm not sure what you intend to do with this. This no longer maintained and contains bugs that are not present in the go version.

**Comment by postacik** [comment]
Just want to check the implementation details. Thank you very much.

**Comment by Florimond** [comment]
Have you solved your problem regarding the occupancy?
If I'm not mistaken, it should be fairly straightforward to compute it on the client side using a Set collection. HashSet in C# and Set in Javascript.

**Comment by postacik** [comment]
I use emitter to send statistics to clients.

Since each statistic is created and subscribed by a single user, I simply check unsubscribe events to delete the statistic.

So I did not need to keep a record of subscribers for my current implementation but as you've mentioned a HashSet would suffice to do it.

Thanks :)
