### ISSUE TITLE
Failover to other cluster node

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#211]
Do the emitter client libraries perform automatic failover to a cluster node when the initially connected emitter node goes down or do we have to keep a list of all emitter nodes to do manual failover?

**Comment by Florimond** [comment]
It's shouldn't be up to the client to choose to which node to connect.
There is an infrastructure part here that I don't know exactly. I'll discuss it with @kelindar when I see him. In the meantime, does this help in any way? [Emitter: Production-Ready Cluster with Kubernetes & Microsoft Azure](https://www.youtube.com/watch?v=4ixnxreKsOg)

**Comment by postacik** [comment]
Simple warm standby implementations I've used keep a list of cluster IPs (generally two) and try to connect to the master node initially. If the master node is not up or goes down after connection, they try to connect to alternative IPs in a round robin fashion.

Is it feasible to implement this algorithm with the C# or Javascript emitter APIs?

And if I lose connection to the master node and connect to the cluster node, is there a way for the cluster to serve me with my previous subscriptions (can I connect it with the same ID)?

**Comment by postacik** [comment]
Hi @kelindar ,
Can you comment on my last question?

**Comment by kelindar** [comment]
There's a few ways of doing this. For production environment I'd recommend having a TCP load balancer in front of the cluster. It is possible to do client side load balancing as well, but I'd avoid stand by mode with emitter as there's no concept of "master" emitter broker, you could simply reconnect to any other broker if you loose connection.

**Comment by postacik** [comment]
Thanks Roman. 

"you could simply reconnect to any other broker if you loose connection"

Does this mean the client library (C#, Javascript or Go) will assure the application will connect to the second emitter instance with the same id and I'll not lose my previous subscriptions?

**Comment by postacik** [comment]
Hi Roman, do you have any comments for the last question?

**Comment by postacik** [comment]
Unfortunately when I connect to a second instance of emitter after a disconnect from the first instance, I get a new id and my previous subscriptions are gone.

**Comment by Florimond** [comment]
Any re-connection is a "clean session". So you have to re-subscribe, and you'll have a new user id. There is no special case for "re-connection" on the emitter side.

**Comment by postacik** [comment]
Thanks @Florimond :)

So this means if you don't have a TCP balancer in front of the cluster, then you have to remember all previous subscriptions and re-subscribe on the other emitter instance. This makes the cluster useless for many use cases.

Can there be an improvement on emitter server and client to simulate master/slave connections.

Client will connect to both servers but send requests only to master and receive messages only from the master. It will only send keep alive messages to the slave server.

If the master goes down, the slave will understand this and notify the client that it took over so the client will forward the messages to the slave which is the new master.

Is this possible with the current architecture?

**Comment by postacik** [comment]
And an extra question. 

Doesn't having a single TCP load balancer create a single point of failure for the emitter cluster?

**Comment by postacik** [comment]
As far as I understand you have no intention to implement a master/slave pattern for emitter.

If you can simply tell me whether it's possible/feasible to implement, I'll try to do it myself.

**Comment by Florimond** [comment]
About the subscriptions, the ideal way to go is to subscribe inside the connection handler anyway. So it will remember to subscribe again after a re-connection.

Sorry for this delay, but about the master/slave thing I'm not sure know how to answer, and @kelindar seems quite busy for the moment.

What I would say is that emitter brokers are designed to be peers at the very core. I don't think it's possible to introduce

**Comment by postacik** [comment]
@kelindar , do you have any comments on this?

**Comment by kelindar** [comment]
You could connect to two different brokers (2 emitter connections) and simulate this pattern in the client. You'd have to pick which broker is a master, as it doesn't really matter for emitter.

Also, on your question about load balancer - you can cluster load balancers too or use cloud load balancer if you're running this on a cloud.

**Comment by postacik** [comment]
Your proposal gives us a warm standby solution.

When connection to master is lost, you have to connect to the slave and remember and re-do everything you did on the master which will need extra handling on the client.

When you have a TCP load balancer in front, you don't have to implement such logic.

To enable hot standby working mode, similar to TCP load balancer, the server needs to implement the switch as I explained in my previous post.

I presume your current implementation of the server is not suitable for this.
