### ISSUE TITLE
About unsafe pointer

### ISSUE THREAD

**Issue by sunface-io** [emitter-io/emitter#22]
I think
``` 
rootPtr := (*unsafe.Pointer)(unsafe.Pointer(&c.root))
	root := (*iNode)(atomic.LoadPointer(rootPtr))
```
is equal to 
```
root := c.root
```

But maybe there is something that i missed here,please tell me why :)

**Comment by Kelindar** [comment]
This is equivalent indeed, but not equal to that, as the swap needs to be atomic.
