### ISSUE TITLE
Subscribe with "sent after date" option

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#220]
Hi,

I plan to use emitter as a broker in a messaging application.

Since the clients will be mobile phones, they will be offline most of the time.

When a mobile client wakes up with a push notification, it will need to retrieve messages in a channel that were sent after the time it went offline.

We can retrieve "the last n" messages in a channel and this may be more than enough for IoT applications but is it possible to retrieve messages "sent after date d"?

Using the current features, I'll have to retrieve all the non-expired messages in the channel and discard the ones I retrieved before, which will cause unnecessary traffic when I use a long TTL (one week maybe).

**Comment by Florimond** [comment]
The code retrieving the `last` messages, already uses a window. See:

`	// Check if the key has a load permission (also applies for retained)
	if key.HasPermission(security.AllowLoad) {
		t0, t1 := channel.Window() // Get the window
		msgs, err := c.service.storage.Query(ssid, t0, t1, int(limit))
		if err != nil {
			logging.LogError("conn", "query last messages", err)
			return ErrServerError
		}

		// Range over the messages in the channel and forward them
		for _, m := range msgs {
			msg := m // Copy message
			c.Send(&msg)
		}
	}`

It shouldn't be too difficult to adapt it and retrieve messages corresponding to a window sent by the client.
However, I'll have to discuss it with @kelindar.

**Comment by kelindar** [comment]
Indeed, the window should be exposed with `from` and `to` options, both of which should be UTC unix time integers in seconds.

**Comment by postacik** [comment]
@kelindar , does your answer mean that it can be done?

**Comment by Florimond** [comment]
I wrongly implied some modification to the broker was needed. Actually, the feature is already fully implemented.
What is needed is our various lib to expose the feature.
You can provide in the channel a parameter `from`, and a parameter `until`. Both have to be a timestamp in full seconds.
You currently also have to set the parameter `last` (ex: 10000) to receive your "full" history between the dates you sent. I wonder whether this last thing is something that could be confusing and should be changed...

**Comment by postacik** [comment]
That's great news, thanks.

It would be less confusing if the function would return all the messages between the specified dates if last parameter is null. Though it can be set to a max int value to do the same thing.

However it's meaningful to use it to return last n messages between the specified dates.

I'll test it with my Flutter library.
