### ISSUE TITLE
Delete/Drop/Edit Channel  from Broker

### ISSUE THREAD

**Issue by WBangash** [emitter-io/emitter#222]
Hi there,
Once i create a channel key using keygen then i realise that i don't need this channel and i have to create with new name. I cannot edit channel property right? 
I have the following questions.

what will happen to the channel i created with empty "ttl" and i don't need it. ?
How can i get list of channel from the broker ?
How can i delete an unwanted channel?

**Comment by Florimond** [comment]
You can't "create" a channel, you create a key. A channel has no physical existence beyond to key used to publish and subscribe. Every information about the channel is embedded into this key. The ttl of the channel is extracted from the key and checked when you publish or subscribe using the key, to check whether you have the right to do so.
At a instant T, if is no message saved for a channel (using the ttl when publishing), there is simply no information about this channel on the server.

**Comment by WBangash** [comment]
Thank you so much for quite good explanation. But what about a key. Can we edit or drop Key from the broker ?. for example  i want to drop a key  or i want to access all the keys list created from the broker. 
i apologise if it doesn't make sense.

**Comment by montanaflynn** [comment]
The docs are not really clear:

> > Ttl: The time to live describes how long the channel key should be valid. The unit for this is seconds. When this time has passed the channel will still exist, but a new channel name needs to be generated to be able to publish or subscribe using this channel. A finite time to lives can be used to increase security. Ttl is optional, if you leave it empty the time to live is indefinitely.

This makes it seem like if you create a key for a channel you cannot use the channel with other keys. Maybe there's a typo and it meant to say:

>but a new channel *KEY* needs to be generated to be able to publish or subscribe using this channel.

I'm also interested in how we can delete old channel keys that are no longer in use.

**Comment by Florimond** [comment]
You are right, the documentation is unclear and should be updated.

Well, keys are not stored either. It's up to you to store it and provide it when needed. So there is nothing to "delete them". They just become invalid when the TTL they embed expires.

**Comment by montanaflynn** [comment]
Thanks, this makes more sense now! I guess the only way to "remove" keys that don't have a `ttl` is changing the secret key that was used to generate them.

**Comment by kelindar** [comment]
@montanaflynn fyi https://github.com/emitter-io/emitter/pull/317
