### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by montanaflynn** [emitter-io/emitter#225]
I've noticed emitter is very verbose when it comes to logging, especially for each connection. Looking at my server logs there are thousands of lines like this:

```
2019/04/29 10:13:34 [conn] created (AWBUHI7HWQSJD3MKF2AYXYSGWY)
2019/04/29 10:13:34 [conn] closed (AWBUHI7HWQSJD3MKF2AYXYSGWY)
2019/04/29 10:13:34 [conn] created (LYPM3M22JBUGZKD3UBFFNDUPZQ)
2019/04/29 10:13:34 [conn] closed (LYPM3M22JBUGZKD3UBFFNDUPZQ)
```

How can we disable these logs?

**Comment by kelindar** [comment]
Good point, I think we can get rid of those logs in the first place.
