### ISSUE TITLE
http DOCTYPE error on /keygen

### ISSUE THREAD

**Issue by robotamer** [emitter-io/emitter#227]
I have tried firefox, chrome and couple more browsers all on linux/debian.
I am keep getting the html source displayed in the browser. The browser doesn't seam to accept the html doctype I guess.
Attached is a screenshot.

![mqtt-2019-05-04 00-20-30](https://user-images.githubusercontent.com/217512/57166746-c6c0eb80-6e03-11e9-9b0a-87e081df1fa3.png)

**Comment by kelindar** [comment]
Could you try this branch https://github.com/emitter-io/emitter/pull/231 to see if the bug still persists ?

**Comment by robotamer** [comment]
Looks like it is working  
Thank you
