### ISSUE TITLE
Make keygen a local resource

### ISSUE THREAD

**Issue by sarge** [emitter-io/emitter#229]
Hi there,

Wondering if keygen should be a local resource, as access to the secret key requires additional protection. The concern would be if the s3 bucket was compromised then secrets could be ex-filtrated.

Possible solutions would be to embed the html / js to mitigate this.

**Comment by kelindar** [comment]
@sarge You're right, this needs to be embedded instead of loading externally.

**Comment by sarge** [comment]
@kelindar Perhaps a simpler option would be make this a server side page - no js - simple for post?
