### ISSUE TITLE
Where did emitter cloud go?

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#233]
Hi,
Security page on emitter.io is gone. Did you stop giving the cloud service?

Regards

**Comment by postacik** [comment]
I could reach the login page using https://emitter.io/login.

Did you remove the links from the main page?

**Comment by kelindar** [comment]
@postacik Sadly, we are sunsetting emitter cloud in order to fully focus on the open source version of emitter. This decision wasn't easy for the team and has been primarily driven by personal reasons and lack of adoption of emitter cloud.

**Comment by postacik** [comment]
Does this mean you are going to shut down the current working server some time in the future or will it be running for the current users?

**Comment by Florimond** [comment]
The servers are now down as well.
