### ISSUE TITLE
Can I get the secret key again by license.

### ISSUE THREAD

**Issue by zsimple** [emitter-io/emitter#236]
I ran emitter and it show me the license and secret, and then I can use the license to run server very easily, it is really a very kindy tool.

While I dont write secret key down, now I cant find it anywhere. Of course I can rerun emitter to get another license/secret, but all the generated channel keys will be unusable. Is there an easy way to find the correct secret key again(by the current license)?

**Comment by Florimond** [comment]
There is currently no way of generating a new secret key based on a license. But we could make a tool for that.

**Comment by zsimple** [comment]
It will be a big helpfull tool for some careless guys like me, or just emebed this function into server as an option, like `./emitter --recover-secret {license}`?
