### ISSUE TITLE
Sending multiple 64KB packets in order

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#237]
Hi,

We are using emitter to execute remote procedure calls on a server.

Sometimes, the result of an RPC is longer than 64KB (upto 1 MB).

We plan to gzip the result, split it into n 64KB segments and send the packets with segment id prefixed (1-n).

Which qos type should we use while sending the packets so that they will be delivered in order? (Getting them in order is not mandatory but ensuring packet delivery is.)

Would sending the packets within the maximum limits effect emitter performance?

**Comment by postacik** [comment]
Any comments on this?

**Comment by kelindar** [comment]
@postacik Good question. Emitter broker does not guarantee message ordering, and messages might come to the consumer out of order as it heavily depends on the actual routing.

For your case, if you really require sending large payloads back to the client you might indeed need to consider compression and fragmentation with an ordered ID so you can manually reconstruct them on the consumer.  This is similar how [IP works](https://en.wikipedia.org/wiki/IP_fragmentation).

For QoS I'd suggest using QoS `1` to make sure the packets make it to the broker in first place.

**Comment by postacik** [comment]
Thanks for the answer.

Would sending the packets within the maximum limits effect emitter performance?

**Comment by kelindar** [comment]
It will as you're going to have more traffic moving through the cluster network. However, it should still work fine. Let us know if you experience any slowdowns and we could have a look.
