### ISSUE TITLE
weave development is dead

### ISSUE THREAD

**Issue by ghost** [emitter-io/emitter#240]
It looks like development on Waev is dead.
https://github.com/weaveworks/mesh/pull/99

**Comment by kelindar** [comment]
We're going to form it to make sure it suits emitter network.

**Comment by joeblew99** [comment]
hey @kelindar boy that was a quick response :)

When you say "form" it, i think you mean "fork" it right ?

Would be really interested in working on that.

**Comment by kelindar** [comment]
Yeah, will have a PR for this. There's bunch of in efficiencies I've identified in their network stack and wanted to improve.

**Comment by faceair** [comment]
Is [hashicorp/memberlist](https://github.com/hashicorp/memberlist) a good replacement ?
