### ISSUE TITLE
Status and stability of client SDKs (esp. Java/Android)???

### ISSUE THREAD

**Issue by StephanSchuster** [emitter-io/emitter#242]
I am currently evaluating emitter.io as an alternative to deepstream which has some outdated and buggy client SDKs, especially when it comes to Java/Android.

First, I was very happy when I read about the concepts of emitter.io and excited to give it a try. But looking at your different client SDKs I am totally irritated about their (mostly) outdated status and little stars (esp. Java).

To me it just does not make sense to develop further only the server side without keeping all clients up to date? The best server does not work without a client, right? Or am I missing something and all of your client SDKs are stable, aligned, up to date, usable and working? At least when it comes to Java/Android the latter does not seem to be the case: [see here](https://github.com/emitter-io/java/issues/2)

I understand that this is an Open Source Project. And a quite good one indeed. So please don't get me wrong. I just wanted to ask for a bit more insight into your "strategy". After deepstream this is now the second, very promising "realtime server project" which suffers from this client SDK issue. And this is just so sad.

**Comment by postacik** [comment]
I agree with @StephanSchuster about this issue.

I used the Javascript, Go and C# SDKs upto now and I can say they don't share similar functions and the other ones are not equal to the Go SDK which I think is the most mature one.

So I've built my own Dart, JavaScript and C# client libraries which look and feel the same as possible as can be and it took really great amount of time.

**Comment by Florimond** [comment]
The C# and Java SDKs are the oldests, while the Go lib was entirely rewritten recently.

I rewrote the Python lib taking the Go SDK as a model. And I intend to do so for the other SDKs as far as possible.

--
Since we are talking about SDKs and their features. In the Go SDK, do you @postacik set the `OnMessage` handler, or do you always set the `optionalHandler` when you subscribe (which stores the handler into the trie)?
We are thinking of removing the `OnMessage` and only keep the trie...

**Comment by postacik** [comment]
I do not use the Go SDK really. It is only a model to find out how things are done for building other libraries.

If the trie peforms better than switch case statements it may be better to use it instead ot the generic onMessage handler but I think onMessage should stay. 

I once used comet-d and was happy with a generic message handler as far as I can remember.

**Comment by postacik** [comment]
I updated the dart library with async functions and I modified the original JavaScript library with similar functions. However I don't have time to create a pull request but I can share it if you want to use it as a reference.
