### ISSUE TITLE
How to disconnect client or unsubscribe user

### ISSUE THREAD

**Issue by XanderDwyl** [emitter-io/emitter#244]

**Comment by XanderDwyl** [comment]
![contact-center-app](https://user-images.githubusercontent.com/5339274/58744213-2a295200-8472-11e9-9179-3cb9df489299.jpg)

**Comment by Florimond** [comment]
You mean, have a client force another client to disconnect? That's not possible.

**Comment by XanderDwyl** [comment]
Thank you @Florimond but is there a way that we can clear a client or reset using the main key from the emitter?
