### ISSUE TITLE
Performance comparisons with other distributed MQTT brokers like emqx/vernemq/rabbitmq?

### ISSUE THREAD

**Issue by elimist3** [emitter-io/emitter#260]
Hey this project looks really cool!

Any ideas how it compares performance-wise to other distributed MQTT brokers like [emqx](https://github.com/emqx/emqx), [vernemq](https://github.com/vernemq/vernemq) or [rabbitmq](https://github.com/rabbitmq/rabbitmq-server)? I wonder how Go compares to Erlang for this type of realtime applications.

**Comment by kelindar** [comment]
We don't benchmark against other products, each stack is different and emitter is not exactly an MQTT broker as it adds a few custom features.

However, we did work on some performance optimisations recently and have added benchmarking capabilities inside emitter. We can do a 2/3 million of tiny messages per second in our benchmark (single broker). 

I would encourage you to benchmark on your own workload and let us know if there's any performance issues.

**Comment by rebootcode** [comment]
@kelindar - providing system specification details with numbers are better to understand. You mentioned 2/3 million of tiny message per second, "what was RAM, CPU, message length". 2 to 3 is a huge difference when a suffix is "million".

**Comment by kelindar** [comment]
Here's one of the tests I ran. Again, I'd encourage everyone to do their own benchmarking as the results will vary depending on the workload.

![image](https://user-images.githubusercontent.com/583116/62141027-813a8e80-b31e-11e9-8825-a3391608dfda.png)

**Comment by behrad** [comment]
@kelindar Was that test publishing with qos 0 or 1?

1. Can you elaborate on qos=1 fan-in and fan-out performance?

2. What about message storage type/efficiency for offline messages?

**Comment by shushenghong** [comment]
thanks @kelindar for this great  project,  i'm wondering  can emitter scalable distribute for support  IOT devices cloud center (  billions of connections )?
