### ISSUE TITLE
Private link question

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#261]
Hi,
I create a key for a channel using the following function on the server:

`emitter.keygen({ key: secretKey, channel: "test/", type: "rwe", ttl: 0 });`

This key is presented to a client and it creates a private link using the following command:

`emitter.link({ key: key, channel: channel, name: shortcut, private: true, subscribe: true, ttl: 0, me: false });
`
Then the client can publish messages to this private channel: 

`emitter.publishWithLink({link: shortcut, message: "Hello world from link"});`

However, the client can also subscribe to the "test/" channel using this key because it has "r" permission to subscribe to the private channel.

This is a security flaw, which lets a client with the key to subscribe to the root channel and listen to other subscribers' private channel messages under the same root.

What would you suggest to do for this problem?

Should I create a different root channel for every client?

**Comment by kelindar** [comment]
@postacik Thanks for bringing this up. I think you're correct and it poses a problem - would appreciate a review on this PR which should fix the issue on the broker https://github.com/emitter-io/emitter/pull/262. 

The simple solution for this is to disallow all publish/subscribe on the key which has `extend` permission. Once the private link is created, it is created with the same permissions but removing the `extend` from it.

**Comment by postacik** [comment]
I had a look at the changes in internal/broker/handlers.go but really could not understand your aim.

I personally would change the keygen function to correct this problem:

For example the following request must create a key for channel `"test/{userid}"` with `"rwe"` permissions.

`emitter.keygen({ key: secretKey, channel: "test/", type: "**e**", ttl: 0 });`

So the client will be able to create a private link, subscribe and publish on his private channel.

**Comment by postacik** [comment]
"The simple solution for this is to disallow all publish/subscribe on the key which has extend permission. Once the private link is created, it is created with the same permissions but removing the extend from it."

Maybe you're saying the same thing with these sentences but I could not be sure.

**Comment by postacik** [comment]
I looked at your PR again and now it looks reasonable.

Now, I have to create a key with only "e" permission on the server. If I add other permissions I'll get an error from Emitter.

This key will let the client to create a link, subscribe and publish to the link.

Am I right?

**Comment by postacik** [comment]
In the current implementation, If don't use the "r" permission while creating the key, subscribe = true option does not work when I create a link on the client and I don't get the messages published to my private link by the server.

I could not see the code part which corrects this in the PR.

**Comment by kelindar** [comment]
I have yet to test it, but here's the proposed flow in the PR:

You can generate a key for the client which would have `rwe` permissions.
```
key = emitter.keygen({ key: secretKey, channel: "test/", type: "rwe", ttl: 0 });
```

On the client, using this key you can create a private link and publish to it (or subscribe).
```
emitter.link({ key: key, channel: channel, name: a, private: true, subscribe: true, ttl: 0, me: false }); 
emitter.publishWithLink({link: a, message: "Hello world from link"});
```

The only thing the PR fixes is that if you use the `key` above fo subscribe or publish directly, you will get an error. This basically makes keys which have `e` only usable for extension purpose (aka creating private links).
