### ISSUE TITLE
Cannot register: "Unable to continue"

### ISSUE THREAD

**Issue by chanibal** [emitter-io/emitter#263]
Hi, I wanted to test your service but it looks like you've got an issue at your website and registration is impossible.

![image](https://user-images.githubusercontent.com/697605/62624254-fdd2fb80-b922-11e9-8e69-c563b01bbfbc.png)

**Comment by kelindar** [comment]
Yes, we do not offer the cloud sandbox anymore. Must be a rogue link that brought you to an old page.

**Comment by chanibal** [comment]
The rouge link was from Espressif's MQTT component for ESP32 example:
https://github.com/espressif/esp-mqtt/tree/master/examples/emitter-client

**Comment by mak-balendin** [comment]
## Not able to Register

![image](https://user-images.githubusercontent.com/64409370/99647291-96897e00-2a77-11eb-8ae0-08139e0f3e57.png)


![image](https://user-images.githubusercontent.com/64409370/99647333-a4d79a00-2a77-11eb-9831-834eb9b29000.png)
