### ISSUE TITLE
Two questions on network connection drop handling and max-limit of connections

### ISSUE THREAD

**Issue by RedhwanAhmed** [emitter-io/emitter#266]
Hello everyone. I am trying to use Emitter as notification service for a web application.

Can anyone help me understand how connection, re-connection and termination happen.

1. If receiver connection drop, do emitter auto-terminate the connection. Is it possible to run out of resources if receivers keep dropping the connections?

2. Is there a limit to the web socket/tcp connection emitter can make, and where to find it.?

**Comment by kelindar** [comment]
1. If TCP connection is terminated properly, it's all good. If a TCP connection is not terminated and the client is gone, broker will timeout the connection.
2. Not in the broker, but this could be controlled using ulimit in Linux.

**Comment by RedhwanAhmed** [comment]
Thank you.
