### ISSUE TITLE
What is License and Secret Key? Why do we need them?

### ISSUE THREAD

**Issue by rebootcode** [emitter-io/emitter#269]
Hi, 

I planned to use emitter, but all of a sudden - I read in QuickStart (https://github.com/emitter-io/emitter#quick-start)

```
[service] generated new license: uppD0PFIcNK6VY-7PTo7uWH8EobaOGgRAAAAAAAAAAI
[service] generated new secret key: JUoOxjoXLc4muSxXynOpTc60nWtwUI3o
```

What are the license and the secret key here? Why do we need them?

Is Emitter - Software as a service or Platform as a service system?
If we use emitter, all the data are stored remotely to other servers? What is Emitter and Why those keys are required?

Thanks

**Comment by Florimond** [comment]
All the servers in a cluster need to share the same license.
The secret key derives from the license, and allows you to generate keys for channels.

Emitter can be deployed as SaaS.

Basically, you want to create your own cluster, and your data is stored only in this cluster.

**Comment by rebootcode** [comment]
It's still confusing;

- Will emitter.io have access to data stored in my cluster in any form?
- Will emitter.io have any types of access to my cluster?
- Does emitter.io have any restrictions on my usage? 

I plan to use it for chat database in one of my product. 
- Is there any restriction coming from emitter.io in any form?

**Comment by Florimond** [comment]
> Will emitter.io have access to data stored in my cluster in any form?
No.

> Will emitter.io have any types of access to my cluster?
 No.

There are restrictions on the source code, as stated by the AGPL. For example, you can't modify Emitter's source code without redistributing it under the same license.

**Comment by rebootcode** [comment]
Great! Thanks

> There are restrictions on the source code, as stated by the AGPL. For example, you can't modify Emitter's source code without redistributing it under the same license.

Yes, I accept and appreciate the developer's AGPL license. For 100%, whenever source code will be modified for my use case, I will release them with same AGPL license back.

Thanks
