### ISSUE TITLE
Emitter server logging

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#271]
Hi,
Is there a way to enable debug logging in emitter? 

If an emitter server is facing the Internet, there will be a need at least to log the IP addresses of the requests for security.

Is it feasible to add such a feature to emitter (if it already does not exist)?

**Comment by kelindar** [comment]
What kind of information would you require?

**Comment by postacik** [comment]
Something like the Apache web server access log:

192.168.2.20 [28/Jul/2006:10:27:10 -0300] "GET /cgi-bin/try/ HTTP/1.0" 200 3395

It may include the IP address, timestamp, request (publish/subscribe/keygen...), result (200,400) 

+ subscriber id

And it can also include an error log like the following to detect fraud attempts:

[Fri Dec 16 01:46:23 2005] [error] [client 1.2.3.4] Directory index forbidden by rule: /home/test/

You can check Apache error logs in the following document:
https://ossec-docs.readthedocs.io/en/latest/log_samples/apache/apache.html

**Comment by postacik** [comment]
Do you have any plans to implement this?
