### ISSUE TITLE
multi channels grant in single keygen request

### ISSUE THREAD

**Issue by himadrinath** [emitter-io/emitter#273]
how can i generate key for multiple channels in a single keygen request. 
```

 emitter.keygen({
	key: "<your secret key>",
	channel: "chat/#/",
	type: "rwls",
	ttl: 600
}); 
```

**Comment by Florimond** [comment]
Well you can generate a key that will be valid for subchannels as well.
But you cannot generate a key for multiple base channels at once.

In other words you'll generate a key for "chat" and "chat/foo/bar", but you can't generate a key or multiple keys for "chat" and "foo" with one request.

**Comment by himadrinath** [comment]
@Florimond thanks. another thing in csharp keygen request return type this void it creating little bit of problem is their way to change it
