### ISSUE TITLE
dev cors

### ISSUE THREAD

**Issue by crapthings** [emitter-io/emitter#274]
```js
import React, { Component } from 'react'
import emitter from 'emitter-io'

export default class extends Component {
  componentDidMount() {
    this.client = emitter.connect({
      host: '10.0.0.103',
      port: '8082',
    })

    this.client.subscribe({
      key: 'wow',
      channel: 'demo/',
    })
  }

  render() {
    return (
      <div className="content-responsive">
        chat
      </div>
    )
  }
}

```

Access to fetch at 'http://10.0.0.103:8082/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

i proxy with nginx but sstill get this

**Comment by postacik** [comment]
Strange. I'm using Chrome Version 76.0.3809.132 (latest I think) and connect to my emitter server directly and do not get such a CORS error.

**Comment by postacik** [comment]
And CORS should not be applying to websocket communication.

https://blog.securityevaluators.com/websockets-not-bound-by-cors-does-this-mean-2e7819374acc

**Comment by crapthings** [comment]
i've change this line import emitter from 'emitter-io' to use cdn

the error goes

so  emitter-io can be only used with node.js?
