### ISSUE TITLE
Can i remove message after delivery?

### ISSUE THREAD

**Issue by crapthings** [emitter-io/emitter#275]
i've set publish ttl? any possible to remove the message after user receive?

**Comment by kelindar** [comment]
TTL will automatically delete the message when expired. In your case, you might want to keep a set of received message IDs on the client and simply ignore them if received twice.

**Comment by giter** [comment]
@kelindar  What if I have a lot of devices with several period subscribes every day ? I would receive same messages at every time?

**Comment by giter** [comment]
and how can I know the Message IDs by using client driver ??
