### ISSUE TITLE
How to learn the version of a binary

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#280]
Is there a way to learn the version of an emitter binary?

Where in the source code is the version number defined ?

Is it possible to learn the version of the server from the client side?

**Comment by kelindar** [comment]
I'm adding this `version` command to the binary for now: https://github.com/emitter-io/emitter/pull/284

**Comment by postacik** [comment]
Thanks. This might be an important information for client sdk users because some features are being removed in  new versions. Can you also send it as a parameter in the reply of emitter/me request?

**Comment by kelindar** [comment]
https://github.com/emitter-io/emitter/pull/286

**Comment by postacik** [comment]
I built the exe with `go build . `and also with `build.bat`.

However it prints the following info when I run `emitter.exe version` for both.

`2019/10/26 12:52:52 [version] emitter version , commit`

**Comment by postacik** [comment]
Hi, am I doing something wrong?

**Comment by postacik** [comment]
Hi @kelindar.  Are you still maintaining this project or are you too busy to look after it?

**Comment by Florimond** [comment]
Hello @postacik,

indeed, @kelindar is very busy, but it's temporary.

About the version of the binary in the `me` request, I voted against, for security reasons. I'm no hacker/cracker, but I know the first thing to know when trying to penetrate a system is the version of the software you are trying to crack.

**Comment by kelindar** [comment]
@postacik still maintaining, just a bit busy lately at work. For the version, I need to think a bit more given that I'm setting it in the CI/CD so it only works with "official" builds.

**Comment by postacik** [comment]
Happy to hear that you are still in because this is a great project. Your concern about hackers is right. To be able to see the version from the command line should suffice. Is it not possible to set the version info in a constant variable in the source code?
