### ISSUE TITLE
What happens to channel subscriptions if key expires?

### ISSUE THREAD

**Issue by gtmadev** [emitter-io/emitter#291]
I am wondering about something... you need a key to publish a message and subscribe. You don't seem to need a key to actually connect. So what happens to a subscription when the key times out?

**Example**
I create a key with a TTL of 600. I then subscribe to a channel and wait for messages. What happens to that subscription once the 600 seconds times out? Obviously, I could not publish a message because I would need to provide a valid key in order to publish. But what happens to that subscription that is using my connection and waiting on messages? Does it just stop receiving messages?

The reason I ask is.. I want to an app to know when it needs to go get a new key. An easy thing to do is to check for TTL expiration anytime the app is about to publish a message. This way, we don't have to periodically check the key's TTL. The problem I see is for subscriptions. Since we are simply waiting for messages, we don't have an opportunity to "check". We have to assume that the subscription is still valid and receiving "events".

If the key expires, will an event be raised on the connection or the channel?

**Comment by postacik** [comment]
I can answer this question as a user. 

Key expiration date is only checked when the request is executed on the server. So subscription does not expire and you continue to receive messages. But if the key also has publish permission, you can not publish messages after expiration date.

Please correct me if I am wrong.

**Comment by gtmadev** [comment]
Thanks. And yes, this is what I was thinking might be the case. I just haven't yet tried to test it. But if it does work this way, then I like that I don't have to set timeouts and go fetching new keys just to maintain a subscription. I can just do that right before a client is about to publish.

I'm going to try it out with a few tests and see what happens. Thanks for the feedback.
