### ISSUE TITLE
Presence changes not working?

### ISSUE THREAD

**Issue by millerlogic** [emitter-io/emitter#293]
Hi, I can't seem to get presence changes working. I tried it 3 different ways and all I get is the initial status, but not the changes (change value is true). 

In the [demo-presence](https://github.com/kelindar/demo-presence) after clicking online/offline repeatedly, the "Now Online" remains empty the entire time, and here is the console output:

```
emitter: connected
app.js:64 {time: 1575448858, event: "status", channel: "presence-demo/d797ea7e/", who: Array(0)}
```

I also tested it with sdk-integration-test in go by setting the changes parameter to true in the Presence call, and swapping the order of clientA() and clientB(), again no presence changes.

**Comment by Florimond** [comment]
Hello @millerlogic,

that's odd. Maybe you could give the python testing program a test. 

If you have python installed, just run `sample-python3.py`.
https://github.com/emitter-io/python

![image](https://user-images.githubusercontent.com/372102/70770979-d88e4800-1d6f-11ea-92e2-f89edbb9d8a2.png)

**Comment by twdnhfr** [comment]
i have the same issue with a go client. When new devices connect and publish i get the message but no presenceEvents are fired. 
Also unsubscribe and disconnect do not trigger the event for me. With status: true i get the correct status in that moment.
