### ISSUE TITLE
418000 connection cause memory leak in 8G container

### ISSUE THREAD

**Issue by Estheriii** [emitter-io/emitter#300]
Hi, I run emitter in a 8G container, when the connection grows to 418000, emitter will restart because of memory leak. My question is why one connection cost so large memory? Is that true I can only add 418000 connection in one broker(8G memory)?

**Comment by kelindar** [comment]
Are you talking about 418K concurrent connections? Can you provide us with a test-case which can reproduce the issue?

**Comment by Estheriii** [comment]
Hi, I use Eclipse Paho MQTT Go client to generate connections, I make 100 connection per second, memory grows with the number of connections, when the connection volume reaches 418000, Memory exceeds 8G.

**Comment by Estheriii** [comment]
> Are you talking about 418K concurrent connections? Can you provide us with a test-case which can reproduce the issue?

Hi, I use Eclipse Paho MQTT Go client to generate connections, I make 100 connection per second, memory grows with the number of connections, when the connection volume reaches 418000, Memory exceeds 8G.

**Comment by Estheriii** [comment]
> Are you talking about 418K concurrent connections? Can you provide us with a test-case which can reproduce the issue?

Hi, I just found out that bufio.NewReaderSize eating up a lot of memory, memory cannot be released in time under the high concurrency scenes

**Comment by Estheriii** [comment]
> Are you talking about 418K concurrent connections? Can you provide us with a test-case which can reproduce the issue?

However I change NewReaderSize from 65536 to 256, when the number of connections arrives 469k, client-side occurs  a lot of I/O timeout which make connection stop rising, the memory steady at 4.92G.

**Comment by kelindar** [comment]
@Estheriii have you tried to run emitter in a cluster mode instead of running everything on a single broker?

**Comment by artth02** [comment]
There is any news about it?

I think I have the same problem(or seems to be). In my case, when I get high concurrency(300K or more I start to get pod restart because of "sync: concurrent map iteration and map write on Map error". I think it is because a high memory usage.
I tried to create new clusters but when I have more then 2, they starts to crash randomically too 🤔

**Comment by kelindar** [comment]
This "concurrent map iteration and map write on Map error" looks like a data race, missing lock somewhere. Please provide a way to reproduce (e.g. a unit test which shows a data race or something else), we can have a look and fix this.
