### ISSUE TITLE
Load Balancer for emitter

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#303]
What kind of a load balancer is needed for emitter clusters?

Would a layer 4 load balancer like gobetween be suitable?

**Comment by kelindar** [comment]
Yeah, just a TCP load balancer will do.

**Comment by postacik** [comment]
Which load balancer do you prefer in your installations? Do you have a sample load balancer configuration file for your setup?

**Comment by kelindar** [comment]
If you’re on a cloud, I would just use the load balancer it provides (e.g NLB on AWS).

**Comment by postacik** [comment]
No, we are running emitter on-prem. Do you have any experience with on-prem load balancer config?

**Comment by postacik** [comment]
We made tests with gobetween ( https://github.com/yyyar/gobetween ) using the following test configuration:

```
[servers.sample]
bind = "localhost:3000"
protocol = "tcp" 
balance = "roundrobin"
max_connections = 10000
client_idle_timeout = "10m"
backend_idle_timeout = "10m"
backend_connection_timeout = "2s"

[servers.sample.discovery]
kind = "static"
static_list = [
  "localhost:8082 weight=5",
  "localhost:8083 weight=5"
]

[servers.sample.healthcheck]
fails = 1                      
passes = 1
interval = "2s"   
timeout="1s"             
kind = "ping"
ping_timeout_duration = "500ms"

```

A client connects to the load balancer port 3000.

Then we shut down the emitter cluster node it's connected to.

Current client connection is closed and it connects to the other cluster node through the load balancer.

However we were expecting that the client would not be disconnected and continue its work seamlessly.

Is this because of the load balancer we use or do you have the same behavior with NLB on AWS?

**Comment by postacik** [comment]
Ok, the last one was a dummy question. Closing...
