### ISSUE TITLE
Presence issue in cluster mode

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#304]
Hi,

We have a problem with the following scenario:

A is connected to cluster1 and subscribes to "channel/" and also subscribes to presence of "channel/".
B is connected to cluster2 and subscribes to "channel/" and also subscribes to presence of "channel/".

When A disconnects from cluster1, B gets an "unsubscribe" event with the id of A.

But when cluster1 goes down while A is still connected, B does not get an "unsubscribe" event.

Is this behavior by design or is it a bug?

**Comment by postacik** [comment]
Can you please comment on this. We built one of our functionality on the presence events and this behavior makes our algorithm useless.

**Comment by postacik** [comment]
Any comments?

**Comment by Florimond** [comment]
Hello @postacik,

I'll have a look, discuss it with @kelindar as soon as he is available, and come back to you ASAP.

**Comment by postacik** [comment]
Thanks :)

**Comment by postacik** [comment]
I think a cluster does not keep subscribed channels on other clusters. Is that right?

**Comment by postacik** [comment]
Anything?

**Comment by kelindar** [comment]
@postacik sorry have been busy lately. I'll have a look, but by the sound of it it sounds like a bug. I'm thinking that it could be fixed by brokers having a sort of "heartbeat" for presence and if a server goes down others can remove the connection from the presence list and hence send the event. The downside is that you might receive the "disconnect" event multiple times in case of several brokers decide to clean it up at the same time.

**Comment by postacik** [comment]
Thanks. Having multiple disconnect events would not be a problem.

**Comment by postacik** [comment]
Hi @kelindar , any news about this bug?

**Comment by postacik** [comment]
Hi @kelindar , I hope you're well during these quarantine days. Have you had any chance to look at this issue?

**Comment by kelindar** [comment]
Hi @postacik sorry I've been quite busy these days. Still alive and good, but didn't have much time yet to look into this.

**Comment by postacik** [comment]
Thanks, I'll test it asap.

**Comment by postacik** [comment]
Hi @kelindar , it seems to be fixed according to my very first tests. 

We are using the "gobetween" load balancer in front of emitter clusters and trying to build a keep-alive algorithm, monitoring the presence events on a specific emitter channel.

Using this algorithm, our application servers will decide which one is primary and which one is backup.

Thanks again.
