### ISSUE TITLE
Website registration fails

### ISSUE THREAD

**Issue by ruralcoder** [emitter-io/emitter#306]
I am unable to Register using your site

[https://emitter.io/login/](https://emitter.io/login/
)

I get the message

```
Unable to Continue
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1"> <TITLE>ERROR: The request could not be satisfied</TITLE> </HEAD><BODY> <H1>504 ERROR</H1> <H2>The request could not be satisfied.</H2> <HR noshade size="1px"> CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner. <BR clear="all"> If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. <BR clear="all"> <HR noshade size="1px"> <PRE> Generated by cloudfront (CloudFront) Request ID: ZXIkDRsWKiUhmKkM2WTZKbqJn481bxVTjHFt34DyfoempBp3tI2eRg== </PRE> <ADDRESS> </ADDRESS> </BODY></HTML>
```

**Comment by Florimond** [comment]
Hello,

unfortunately, our internal cloud is currently on hold, and that's why this link you followed is not advertised on our website anymore. I don't know where you got it.
We will probably restart that offer in the near future, but currently you have to start your own server in order to test Emitter.

**Comment by ruralcoder** [comment]
No worries. Here is where I got it yesterday.

<img width="1063" alt="Screen Shot 2020-02-25 at 11 02 32 AM" src="https://user-images.githubusercontent.com/12993309/75278291-76fe4700-57be-11ea-8dda-35aeb0a9052c.png">

<img width="1207" alt="Screen Shot 2020-02-25 at 11 01 29 AM" src="https://user-images.githubusercontent.com/12993309/75278310-7f568200-57be-11ea-85d3-2bab4d620a8a.png">
