### ISSUE TITLE
Probable memory leak

### ISSUE THREAD

**Issue by a1730** [emitter-io/emitter#307]
Hi,
I am testing emitter as a MQTT broker and noticed memory creeping up without any client connection.
I am unable to get emitter version from the running instance but it was v2.704 download from [github](https://github.com/emitter-io/emitter/releases/download/v2.704/emitter-linux-amd64) 
`
prodcdn:~> uname -a
Linux prodcdn 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

prodcdn:~> /tmp/emitter-linux-amd64 -c emitter.conf version  
                                  Error: incorrect usage

Usage: emitter [ -c=<configuration path> ] COMMAND [arg...]

Runs the Emitter broker.
Options:
  -c, --config   Specifies the configuration path (file) to use for the broker. (default "emitter.conf")
Commands:
  load           Runs the load testing client for emitter.
  license        Manipulates licenses and secret keys.
`
Using htop on debian buster, emitter starts with 11m resident memory, grows to 14m in short order. I then leave it running for 1 hour after which the resident memory grew to 21m. Something is off somewhere.

Please note, this is an idle broker with no client connection.

**Comment by kelindar** [comment]
There's some caching and memory could grow indeed. It's unlikely that there is a memory leak at this point in time as we've been running the brokers for months. I may be missing something tho, you can try doing a couple of pprofs to see what's growing in your end.
