### ISSUE TITLE
MaxMessageBytes returns the configured max message size, must be smaller than 64K.

### ISSUE THREAD

**Issue by aibeb** [emitter-io/emitter#309]
why?

`func (c *Config) MaxMessageBytes() int64 {
	if c.Limit.MessageSize <= 0 || c.Limit.MessageSize > maxMessageSize {
		return maxMessageSize
	}
	return int64(c.Limit.MessageSize)
}`

**Comment by kelindar** [comment]
64K is defined by MQTT standard.
