### ISSUE TITLE
Option to have a default TTL for published messages

### ISSUE THREAD

**Issue by iwillflytothemoon** [emitter-io/emitter#327]
Hi, I read the docs about "Message Storage > Storing Messages". Is there a way to set it by default in the configuration? I am using a MQTT client to test the pub/sub and met a deadend on how I can make the published message persistent.

Additional, when will the stored message expires? Upon consumption of all the subscribers or it depends on TTL?

**Comment by Florimond** [comment]
I don't think there is. 

You have to set the ttl with every message you publish.

**Comment by iwillflytothemoon** [comment]
I watched "Emitter: Using MQTT Spy with Emitter" and somehow understand how I can make pub/sub work in a MQTT client. Is there a way to set the ttl in MQTT client? (like how the generated key and channel works)

**Comment by kelindar** [comment]
A bit late to the party. There's actually a `retain` configuration which can be set on the `storage` config. The default is 30 days.
```
"storage": {
	"provider": "ssd",
	"config": { 
		"retain": 2592000
	}
}
```

**Comment by postacik** [comment]
Hi @kelindar , it would be nice to add this to the readme file. :)
