### ISSUE TITLE
Excuse me, is there a C language client

### ISSUE THREAD

**Issue by hansengao** [emitter-io/emitter#331]
Excuse me, is there a C language client
thanks

**Comment by Florimond** [comment]
Hello,
the thing, last time I checked, there was multiple mqtt C library, each with different features, each tailored for a particular purpose. So I decided to not make a choice, and let C programmers do their own implementation for their particular needs. It should be relatively easy.
I once wrote a little tutorial aiming at getting you started with the writing of a SDK: https://github.com/Florimond/tuto-write-emitter-sdk
It's a bit old (there is emitter cloud anymore), but you should still find some relevant information in it. For the rest, you can read the Go SDK to get inspiration, which is the most advanced.

**Comment by hansengao** [comment]
hello , Thank you very much.
