### ISSUE TITLE
Delay in delivering retained message after subscribe

### ISSUE THREAD

**Issue by notonestepback** [emitter-io/emitter#332]
There is delay in delivering retained message after channel subscribe. retained messages are very small, several bytes. consumer and broker are in same network. system is not on production yet so there is no load. retained message store is 10k disk. subscriber is javascript client. retained message delay is around 3 seconds after subscribe.

**Comment by kelindar** [comment]
Which message storage configuration are you using? We don't have a specific delay, but haven't measured this explicitly either.

This is post connection, are you sure it's not the connection that takes a while to be established?

**Comment by notonestepback** [comment]
> Which message storage configuration are you using? We don't have a specific delay, but haven't measured this explicitly either.
> 
> This is post connection, are you sure it's not the connection that takes a while to be established?

hello. storage configuration is ssd but it is regular 10k disks. this is not connection because as we see in logs retained message is delivered in about 3 seconds after subscribe request. this happens only on linux. on windows everything seems ok.
we have got another question. is there possibility to delete retained messages? for some brokers retained messages are working differently i mean retained message is only one and all subsequent message with retained flag will overwrite it. in our case we need retained messages only to get latest state from channel on subscribe. is there possibility to achieve same semantics here? we will have same ttl for all retained messages so there will not be chance to get older state but will not it create too much load on server? i mean maintaining such amount of retained messages when channel count is big and updates are frequent

**Comment by kelindar** [comment]
I think you might be hitting the 2 second timeout on distributed gather (see: https://github.com/emitter-io/emitter/blob/master/internal/provider/storage/ssd.go#L139) as the broker which receives the subscription attempts to gather all of the messages from all of the connected brokers. It may be either a bug in our code or in the network setup if the brokers are unreachable for some reason.

For your other question, it is not currently possible to delete retained messages but I would like to implement such functionality in future.

**Comment by yunfuyiren** [comment]
will the emitter support QoS2, in some day?
