### ISSUE TITLE
MQTT QoS 1 message persistance

### ISSUE THREAD

**Issue by StenGruener** [emitter-io/emitter#334]
Dear community,

does emitter have a feature to persist qos1 messages to ssd storage provider once client drops? In my first test with the docker image 

        - name: EMITTER_STORAGE_PROVIDER
          value: ssd
        - name: EMITTER_STORAGE_CONFIG
          value: /data

messages get lost.

Best Regards
Sten

**Comment by kelindar** [comment]
You'll need to send messages with `ttl` set to a certain value for messages to be stored, and the key should have `store` permission.

**Comment by StenGruener** [comment]
Thank you for the answer, @kelindar! How do i set ttl from mqtt client? same holds for the key, I have just generated it and use it as mqtt-topic.

**Comment by kelindar** [comment]
If you're using a generic MQTT client, you can append something like `?ttl=60` to your topic when you publish. For example you can publish on: `LyOL3fhQDfOKyB6PWNkv6vemLSPjP8hf/my-channel/a/b/c/?ttl=1200` with TTL of 1200 seconds.

There's some more info here: https://emitter.io/develop/creating-sdk/

**Comment by StenGruener** [comment]
thanks again @kelindar. this ttl and last paramters it looks to kinda work. However after server reboot it looks like the generated keys are not longer valid. Is this true? How would I fix that?
