### ISSUE TITLE
How to correctly setup secure connection 

### ISSUE THREAD

**Issue by ridwankustanto** [emitter-io/emitter#336]
Hi, I've been trying to setup a secure connection, I followed some example on closed issues, but still couldn't make it works. This how my docker-compose file looks like:

    version: "2"
    services:
        emitter:
        restart: always
        image: emitter/server:latest
        container_name: emitter
        environment:
            - EMITTER_LICENSE=license:3
            - EMITTER_TLS_LISTEN=443
            - EMITTER_TLS_HOST=sub.domain.id
            - EMITTER_TLS_EMAIL=my@email.com
        ports:
            - "8801:8080"
            - "8443:443"

And when I up the container, I got this on my container log:

![image](https://user-images.githubusercontent.com/19152005/99359891-5349d680-28e2-11eb-93fd-b451f01a98dc.png)
it doesn't listen to the tls connection. Did I do something wrong? I appreciate any help, thanks!

**Comment by kelindar** [comment]
Port `:80` should redirect to this container when querying on `sub.domain.id` in your case, this how [letsencrypt ](https://letsencrypt.org/docs/) validates the domain. If you don't have access, the certificate will not be issued and it won't work.
