### ISSUE TITLE
does not support FreeBSD? 

### ISSUE THREAD

**Issue by blusewang** [emitter-io/emitter#339]
```
cat build.bat 
call :build linux arm  
call :build linux amd64  
call :build linux 386  
call :build darwin amd64  
call :build darwin 386   
call :build windows 386 .exe
call :build windows amd64 .exe
goto :end
...
```
looks just support linux darwin and wondows?
have you considered supporting FreeBSD?

**Comment by kelindar** [comment]
I had a look at this, it should be possible to support FreeBSD but there's one package which is platform specific and does not seem to compile. Should be doable to fix it.
