### ISSUE TITLE
Rolling update broker will resulting in error

### ISSUE THREAD

**Issue by L3o-pold** [emitter-io/emitter#340]
If you rolling update your Kubernetes Statefulset for any reason, you will see that broker will try to connect to no more existing pod:

```bash
[swarm] error during gossip (->[x.x.x.x:4000] error during connection attempt: dial tcp 0.0.0.0:0->x.x.x.x:4000: connect: connection timed out)
```

From my understanding, it should be detected by https://github.com/emitter-io/emitter/blob/ad96b72dfb9cb247fda5acea112c6714871e34de/internal/service/cluster/swarm.go#L146 but is not.

**Comment by kelindar** [comment]
This message should be intermittent, since there's a bit of a lag in gossip. After a while it would remove the peer out of circulation, so as long as your cluster is connecting to the newly created peer, you're good.

**Comment by L3o-pold** [comment]
Messages are not harmful but they do not disappear.
