### ISSUE TITLE
Can `emitter` change license from AGPLv3 to LGPLv3?

### ISSUE THREAD

**Issue by cravler** [emitter-io/emitter#362]
mostly other open source brokers (emqx, rabbitmq, ...) have more liberal license, but with AGPLv3 if you using `emitter` even by the web your app must be by AGPLv3.

https://choosealicense.com/licenses/

**Comment by kelindar** [comment]
You can use emitter as part of a website, AGPLv3 is really protecting the project from someone else building a managed service based of emitter and offering it without contributing back to the project. If you're making an app or a website that uses emitter that you host, there's no issue. We could consider moving to [SSPL](https://en.wikipedia.org/wiki/Server_Side_Public_License) though, which makes the distinction more clear.
