### ISSUE TITLE
Dead Project?

### ISSUE THREAD

**Issue by DarkBlaez** [emitter-io/emitter#366]
Is this a dead project? Many of the issues go unanswered. It looked promising as lighter weight than a Kafka stack.

Also I see the statement 3M messages/sec on a single broker. What was the underlying host specs?

DB-

**Comment by kelindar** [comment]
Not dead, just that most of contributors have day jobs and the current situation leaves very little free time. We review code and welcome contributions.

Also, it's not quite a Kafka replacement, more of a pub/sub system with persistent storage build as an AP system. Kafka is quite different.

For the benchmarks, this was on an 8 core intel cpu, don't recall the exact specs. But I recommend you to run a custom benchmark for your workload and not rely on these numbers necessary.

**Comment by DarkBlaez** [comment]
Thanks, that helps. As I wanted something focused on pure pub/sub and have been looking at Emitter for a while. 

Again thanks for the response, much appreciated

DB-
