### ISSUE TITLE
Website Registration Failing

### ISSUE THREAD

**Issue by M4THYOU** [emitter-io/emitter#367]
I'm trying to register for Emitter cloud right now but I am getting 504 errors. See the attached screenshots.

<img width="1064" alt="Screen Shot 2021-04-05 at 8 32 11 AM" src="https://user-images.githubusercontent.com/21285398/113574155-8a96f680-95e9-11eb-99a5-f41e1c03df3a.png">

<img width="563" alt="Screen Shot 2021-04-05 at 8 32 21 AM" src="https://user-images.githubusercontent.com/21285398/113574159-8e2a7d80-95e9-11eb-80d4-29bceaaa366c.png">

**Comment by kelindar** [comment]
Hey, we're not offering hosted version of emitter at the moment, only the open source one.
