### ISSUE TITLE
Mult-region deployment with emitter

### ISSUE THREAD

**Issue by montanaflynn** [emitter-io/emitter#374]
We're using emitter currently in a single region, but planning to go multi-region soon. Wondering if anyone has experience with emitter in multiple regions and if there's anything to watch out for. Basically we use emitter as a PUB-SUB between web browsers and servers.

**Comment by Florimond** [comment]
I can't speak for the whole community, but I consulted with the team at Emitter and we don't think there is anything specific to watch for.

**Comment by kelindar** [comment]
Indeed, everything in Emitter is configured for WAN - shouldn't be any major issues and we ran a single cluster cross Atlantic for a while when we were doing a hosted version of emitter.

**Comment by montanaflynn** [comment]
Thanks
