### ISSUE TITLE
project status update

### ISSUE THREAD

**Issue by AlexeySpiridonov** [emitter-io/emitter#393]
Is the project still supported?  

We need a distributed system for real-time storage of data of the current ip addresses of 5M+ iot devices that connect to multiple geodistributed nodes.  

Can this project be useful for us?

**Comment by Florimond** [comment]
Hello @AlexeySpiridonov ,
To this question, I usually answer that the project is mature enough to require little maintenance. However, I'm aware that there are currently a few unanswered questions and probably a bug or two that are yet to be fixed. I will try to update was needs to be updated very soon. But no, the project is not "dead".

Emitter was designed with iot in mind, so I think it can definitely be useful for you. If you have more specific questions, don't hesitate to ask them here, or at florimond@husquinet.net if you want more privacy. If I don't have all the answers, I'll consult with @kelindar , who is the original engineer behind the project.
