### ISSUE TITLE
Added emitter to https://github.com/mqtt/mqtt.github.io/wiki/server-support

### ISSUE THREAD

**Issue by AnderssonPeter** [emitter-io/emitter#4]
I have added emitter to https://github.com/mqtt/mqtt.github.io/wiki/server-support but i cant seem to find any documentation what it supports more than clustering & websockets.

Whats missing is

- QoS 0
- QoS 1
- QoS 2
- auth
- [bridge](https://github.com/mqtt/mqtt.github.io/wiki/bridge_protocol)
- [$SYS](https://github.com/mqtt/mqtt.github.io/wiki/conventions#%24sys)
- SSL
- [dynamic topics](https://github.com/mqtt/mqtt.github.io/wiki/are_topics_dynamic)
- plugin system

Im not saying you should implement any thing i just wanna know what is supported so i can add it to the table.

**Comment by Kelindar** [comment]
* QoS 0 -> yes
* QoS 1 -> wip
* QoS 2 -> no
* auth -> yes (through keys)
* bridge -> no
* $SYS -> not yet
* SSL -> yes
* dynamic topics -> yes
* plugin system -> not yet

**Comment by AnderssonPeter** [comment]
Thanks i updated the table with the data!
