### ISSUE TITLE
How to restrict client access

### ISSUE THREAD

**Issue by ben-auo** [emitter-io/emitter#429]
The Emitter Team published an [nice video](https://www.youtube.com/watch?v=OcdL_454XT0) showing how to use [MQTT Spy](https://github.com/eclipse/paho.mqtt-spy). Since we're not a Java shop, I was looking for an example using the popular [MQTTX](https://mqttx.app/) client app. After some trial and error, I figured out you need to set the MQTT version to `3.1.1` to connect. Here's an example using TLS:

![connect](https://github.com/user-attachments/assets/39828bbb-4a9d-4faf-b3c7-10cc856b7a65)

That said, it looks like Name and Client ID don't matter and anyone can connect to it. Is there a tutorial for how to restrict access to the Emitter server (e.g. https:myemitterdomain.com/keygen )?

**Comment by ben-auo** [comment]
I guess technically since they don't know the Secret Key, access to https://myemitterdomain.com/keygen doesn't really expose any vulnerability and in order to publish or subscribe you need a valid key and channel. Still, I'd like to know if there were additional ACLs that could strengthen security, such as a whitelist of IPs or Name Client ID basic auth.

**Comment by ben-auo** [comment]
Even better, a conf setting that disables exposing /keygen via URL and instead a CLI option to generate keys instead. A UI is nice for beginners but a local-only CLI option for something as important as keys should be the default IMHO.

**Comment by Florimond** [comment]
Indeed, Emitter uses a subset of MQTT features, and neither Name nor Client ID are part of this subset. The way Emitter works doesn't require all MQTT 3.1.1 features. And even though several features described in MQTT 5.0 are available with Emitter, they might be implemented in their own way not necessarily compatible with MQTT clients that comply with the official specification.

Now, with a basic setup, indeed anyone can start a connection with Emitter. However, without a key to a channel, they won't be able to do anything. The security, in Emitter, is entirely based on those channel keys.

I think other security needs, like restricting access to the keygen page can be addressed using Nginx or any alternative software.

As for integrating keygen in the CLI, it's probably a good idea. Although the use for such a command might be limited to some initial manipulations for testing purposes.

**Comment by ben-auo** [comment]
Sounds good, thanks.
