### ISSUE TITLE
Go! Broker timeout disconnection.

### ISSUE THREAD

**Issue by pauldy1000** [emitter-io/emitter#56]
Hi.

As per my Blog entry (ID pauldy1000, 21 November 2017) and response from Roman I am enclosing the situation and some source code.  I am using the Go! version of the Broker.

My use case is to have a Subscriber connected to the Broker for the length of time I choose.  

For example, I want a Subscriber in the UK to be ready to receive messages from a Publisher in the USA at any time the USA Publisher chooses to publish messages. If the UK Subscriber connection times out after 1 minute of inactivity, how can I detect that the Publisher in the USA has published a message destined for the UK Subscriber if the USA Publisher does not come on-line for 3 hours?

```
Emitter.Connection emitterMagnetLocal = new Emitter.Connection(magnetLocalIPAddress, magnetLocalPort, "myserverkeygoeshere");
emitterMagnetLocal.On(cChannelKeyCommander, channel, (channel, msg) =>
{
   // Message received, go handle it.
   HandleInboundMessage(channel.TrimEnd(new char[] { '/' }), msg);
});
// Wire up the Disconnect event.
emitterMagnetLocal.Disconnected += EmitterMagnetLocal_Disconnected;
// Connect to Magnet.Local emitter.
ConnectToMagnetLocal();  // This is a class member method which connects to the Broker.

When the Broker forcibly disconnects the Subscriber (as above) the Disconnected event handles it:

private void EmitterMagnetLocal_Disconnected(object sender, EventArgs e)
{
   Logging.LogIt(cCodeName + ": Magnet.Local: Disconnected(): Waiting for five second before trying to reconnect.");

   // Wait for five seconds.
   Thread.Sleep(5000);

   Logging.LogIt(cCodeName + ": Magnet.Local: Disconnected(): Trying to reconnect again now.");

   // Try to connect to the magnet local service again.
   ConnectToMagnetLocal();     // This is a class member method which connects to the Broker.
}
```
I have had to architect the "wait 5 seconds then reconnect" due to the forced disconnection by the Broker.  I would much prefer to be able to declare how long I would like to keep the Subscriber connected - even if this is "never disconnect".

I hope this is useful.

Regards,

Paul.

**Comment by Florimond** [comment]
Hi Paul,
thank you for your report. I'm currently on a tight schedule, but I'll try to reproduce the issue on Saturday. I'll keep you posted.

**Comment by pauldy1000** [comment]
Thanks Florimond.

**Comment by pauldy1000** [comment]
Hi Florimond.  Just wondered if you made any changes?  Thanks and regards,  Paul.

**Comment by 127ice** [comment]
@pauldy1000 me too

**Comment by Kelindar** [comment]
Hang on, we're still investigating the issue.

**Comment by Florimond** [comment]
This was a timeout issue. The lastest version of the broker should solve it.

**Comment by Kelindar** [comment]
Right, so let me explain a bit more what was happening there:

- C# Client was configured to send MQTT Keep Alive every 60 seconds.
- Broker has a inactivity timeout which was set way too aggressively, also to 60 seconds. Which basically resulted in the broker disconnecting C# client before it was able to send a keep-alive ping.

@pauldy1000 @127ice Could you guys pull the latest version and check if everything works for you?

**Comment by 127ice** [comment]
@Kelindar Thanks! Problem solved

**Comment by pauldy1000** [comment]
@Kelindar Only just seen this update :-(  Testing this morning.  How can I test to ensure I have brought down the latest build - is there a "-v" or similar option on emitter.exe or is there anything in the source which identifies the latest build ?  Thanks.......Paul

**Comment by Kelindar** [comment]
@pauldy1000 No version number yet, we're planning to add it. If you're using `go get` to download it, you can use `go get -u github.com/emitter-io/emitter`, the `-u` flag will update it.
