### ISSUE TITLE
How to use emitter with a standard MQTT client ?

### ISSUE THREAD

**Issue by yellowiscool** [emitter-io/emitter#59]
Hei, is it possible to use emitter with a standard MQTT client ?

**Comment by Kelindar** [comment]
@yellowiscool have a look here: https://emitter.io/develop/creating-sdk

**Comment by yellowiscool** [comment]
Thanks. Am I doing it correctly ?

#### I go to /keygen and I generate a key for the channel `bonjour`. I get

```json
{
  "status": 200,
  "key": "24XZPg40wydam70RCxbahLNXAW1zZnp-",
  "channel": "bonjour"
}
```

#### I subscribe to `24XZPg40wydam70RCxbahLNXAW1zZnp-/bonjour`

#### I publish to `24XZPg40wydam70RCxbahLNXAW1zZnp-/bonjour`

This doesn't work using MQTT-Spy and MQTT.fx

**Comment by Kelindar** [comment]
Does it work if you add a trailing slash at the end?`24XZPg40wydam70RCxbahLNXAW1zZnp-/bonjour/` We have a strict parser.

**Comment by yellowiscool** [comment]
Ok it works. 

But it also looks like the topic in the received messages is `bonjour/` and not `24XZPg40wydam70RCxbahLNXAW1zZnp-/bonjour/`. So MQTT.fx doesn't display the messages in the `24XZPg40wydam70RCxbahLNXAW1zZnp-/bonjour/` subscription panel.
