### ISSUE TITLE
Increasing Packet Size above 64Kb

### ISSUE THREAD

**Issue by faisalthaheem** [emitter-io/emitter#6]
Need some documentation on adjusting the message size to larger than 64KB. How can this be done?

**Comment by Kelindar** [comment]
It's not really recommended usage of emitter, but you could change it here: https://github.com/emitter-io/emitter/blob/d78b48e9e963735732da8c8aa2df62f7c9e2f8c6/src/Emitter.Runtime/Network/Mqtt/MqttPacket.cs
