### ISSUE TITLE
Emmiter service stops when running in windows

### ISSUE THREAD

**Issue by rmindel** [emitter-io/emitter#65]
Operating System - Windows 10
Commdan - docker run -d --name emitter -p 8080:8080 --privileged --restart=unless-stopped emitter/server

The docker logs for the container -
+ exec emitter
2017/12/21 14:30:12 [service] configured vault username (141-226-237-60)
2017/12/21 14:30:12 [service] unable to find a license, make sure 'license' value is set in the config file or EMITTER_LICENSE environment variable
2017/12/21 14:30:12 [service] generated new license: xO5qGA4_51ipcTwC5bEMZzyEEZdGnXloAAAAAAAAAAI
2017/12/21 14:30:12 [service] generated new secret key: FdM9SngeP6AVNRWlWdICv6VhDGb_cC26
+ exec emitter
2017/12/21 14:30:25 [service] configured vault username (141-226-237-60)
2017/12/21 14:30:25 [service] unable to find a license, make sure 'license' value is set in the config file or EMITTER_LICENSE environment variable
2017/12/21 14:30:25 [service] generated new license: Wwf6d0te6dBqhSEA_x0SJ_kfqJmDphC3AAAAAAAAAAI
2017/12/21 14:30:25 [service] generated new secret key: R-YqI767_1YgAeQcEA-iJB6KQ-ibnNPZ
+ exec emitter
2017/12/21 14:30:52 [service] configured vault username (141-226-237-60)
2017/12/21 14:30:52 [service] unable to find a license, make sure 'license' value is set in the config file or EMITTER_LICENSE environment variable
2017/12/21 14:30:52 [service] generated new license: TxTkcIWYRR3eBQ9C8eGac0qJ3Wb8YGZ1AAAAAAAAAAI
2017/12/21 14:30:52 [service] generated new secret key: T5hRQioeUYodP77-NPaa1cKjpjKpSWLQ
...

As you can see the emitter service stops right after starting and the docker restarts it.

**Comment by Kelindar** [comment]
This is intended behaviour, when you start the service without licence, it generates one. You'll need to get the licence and start the service again with it.

**Comment by rmindel** [comment]
Oh I did not realize that's the intended behavior, It might be better writing this as an extra step in the README in getting started.

Also - I have little to no experience using docker, how do I set the emitter.conf file if it's within the docker container? I can't use -it as the container keeps restarting :(

I tried setting windows environment variable but that didn't work.

**Comment by Kelindar** [comment]
Once the server is started, it will generate a new security configuration, you can then re-run the same command with an additional environment variable -e EMITTER_LICENSE set to the provided value.
