### ISSUE TITLE
Services.Storage is null in default

### ISSUE THREAD

**Issue by kenyeung128** [emitter-io/emitter#7]
Hi,

How should we set up the Services.Storage? seems it's using S3 but missing some guidance. Thanks.

**Comment by Kelindar** [comment]
There's a bit of complexity involved in setting up the S3 storage, we're keeping this open as we'll add more documentation around this. Going forward, we're working on building some default message storage functionality into the broker itself, as we're working towards rebuilding Emitter in Go (nextgen branch).

**Comment by Kelindar** [comment]
New broker provides `inmemory` storage by default. You simply need to add the following to the configuration:
```
"storage": {
	"provider": "inmemory"
},
```
