### ISSUE TITLE
Channel key for multi level channel ?

### ISSUE THREAD

**Issue by alaingilbert** [emitter-io/emitter#71]
I was wondering why when I create a channel key for let say `a/b` or `/a/b` or `a/b/` or `/a/b/`.
I was not able to subscribe to the channel `<channel key>/a/b/`.
I need to create a key for: `a`, and then I can subscribe to `<channl key>/a/b/`.

Is this behavior intentional ? or is it a bug ? or incomplete feature ?
I think it would be nice to be able to create a key for a multi level channel such as `a/b/c/d/` or `a/b/*/` for example.

-----

The code seems to only verify the first part of a channel.
https://github.com/emitter-io/emitter/blob/ccdad30368005ac3f9ca0bfd6782120a92914610/broker/handlers.go#L68
https://github.com/emitter-io/emitter/blob/ccdad30368005ac3f9ca0bfd6782120a92914610/security/channel.go#L47-L50

**Comment by Kelindar** [comment]
This is a shortcoming of our current design & implementation of channel keys. Channel keys right now are fixed-size, XTEA-encrypted buffers, as we migrated the broker from C# to Go we wanted to maintain retro-compatibility on all features and not break anything as much as possible.

This being said, we've been discussing for a while now and we see the benefit of having channels which can secure sub-channels as well. So we're considering a redesign of channel keys to support sub-channels and wildcards.

**Comment by alaingilbert** [comment]
Alright. Thanks for the taking the time to answer this question :)
