### ISSUE TITLE
Subscribe not working as expected (subscribe multi level without asking for it)

### ISSUE THREAD

**Issue by alaingilbert** [emitter-io/emitter#73]
Let say I subscribe to `<channel key>/a/`
I receive all messages for `<CK>/a/b/`, `<CK>/a/b/c/` ... as well.
This behavior doesn't seems normal to me.

-----

Here is a script to reproduce it:

```go
package main

import (
  "fmt"
  "github.com/eclipse/paho.mqtt.golang"
  "time"
)

func onMessageReceived(client mqtt.Client, message mqtt.Message) {
  // Will never be executed.
}

func publishHandler(client mqtt.Client, message mqtt.Message) {
  fmt.Printf("message on topic: %s, Message: %s\n", message.Topic(), message.Payload())
}

func main() {
  rwKey := "bsol8lzYVW_Y_-CU4Mp2Be99WeWNpn6g"
  opts := mqtt.NewClientOptions()
  opts.AddBroker("tcp://127.0.0.1:8080")
  opts.SetDefaultPublishHandler(publishHandler)
  c := mqtt.NewClient(opts)
  token := c.Connect()
  token.Wait()
  token = c.Subscribe(rwKey+"/a/", 0, onMessageReceived)
  token.Wait()
  token = c.Publish(rwKey+"/a/b/c/d/e/f/", 2, false, "TEST")
  time.Sleep(1 * time.Second)
}
```

```
$ go run main.go
message on topic: a/b/c/d/e/f/, Message: TEST
```

-----

**Edit:** According to the tests, this behavior seems to be expected:
https://github.com/emitter-io/emitter/blob/f159aabf092593cf6b433c48f63ea68f78214997/broker/message/subtrie_test.go#L30-L56

But it doesn't seems to follow the MQTT specification:
http://www.steves-internet-guide.com/understanding-mqtt-topics/

**Comment by Kelindar** [comment]
You are correct, this is the current behaviour and not quite the MQTT spec. Do you have a particular use case?

**Comment by alaingilbert** [comment]
I guess I was surprised that let say in this scenario:
```
/us/california/palo-alto-office/workstation1
/us/california/palo-alto-office
```
I register to get messages for my workstation and the office in which I am.
I was suprised to see that I was receiving the messages for all my coworkers as well ! (other workstation in the same office)

I think I will just do:
```
/us_california_palo-alto-office
/us_california_palo-alto-office_workstation1
```
instead. It just does not feel as clean though.

**Comment by alaingilbert** [comment]
I made a patch so the topic matching would follow MQTT specification.
https://github.com/alaingilbert/emitter/commit/b5fbced39f74d62f9270082d5e8efaf5b3933856

I don't really expect this patch to be merge in the main repo since it would be a behavior breaking change.

But yeah if you ever want to have a config to switch between `mqtt topic matching` vs `emitter topic matching`, the code is available.

**Comment by Kelindar** [comment]
I like the idea to making this optional and configurable, but you're right about a breaking change.
