### ISSUE TITLE
Still having issues

### ISSUE THREAD

**Issue by snaquaye** [emitter-io/emitter#75]
#74 I would also want to add, that I can't access the keygen using the url `http://localhost:8080/keygen` and `docker ps` show there is no active emitter-io instance running.

**Comment by Kelindar** [comment]
As I've mentioned, this is intended behavior, when you start the service without licence, it generates one.
You'll need to get the licence and start the service again with `-e EMITTER_LICENSE ...` set. Please refer to the readme, `Quick Start` explains this>
