### ISSUE TITLE
Emitter Publisher-Subscriber Matrix

### ISSUE THREAD

**Issue by omidkrad** [emitter-io/emitter#8]
Hi, I put together this Publisher-Subscriber Matrix to better understand how subscriptions and filtering work in Emitter.

First column is channel to publish to
First row is channel that subscriber is listening to
✔️ Subscriber will receive the message
❌ Subscriber won't receive the message

| Publish to :arrow_down: / Subscriber :arrow_right: | C | C/A | C/+ | C/A/B | C/+/B | C/D |
| ------- | --- | --- | --- | --- | --- | --- |
| C         | ✔️ | ❌ | ❌ | ❌ | ❌ | ❌ | 
| C/A     | ✔️ | ✔️ | ✔️ | ❌ | ❌ | ❌ |
| C/A/B | ✔️ | ✔️ | ❌ | ✔️ | ✔️ | ❌ |
| C/D     | ✔️ | ❌ | ✔️ | ❌ | ❌  | ✔️ | 
| C/D/B | ✔️ | ❌ | ❌ | ❌ | ✔️ | ✔️ |

Can you please verify if this is correct? It would be very helpful if we can add something like this to the documentation. Thanks!

**Comment by VladimirAkopyan** [comment]
are you just trying to figure out how MQTT topics work? This diagram is very confusing

**Comment by omidkrad** [comment]
Thanks for the link, it was useful. I added a legend to the table above to make it more clear.

**Comment by VladimirAkopyan** [comment]
That seems correct to me

**Comment by Kelindar** [comment]
@omidkrad thanks for the suggestion, added here: https://emitter.io/develop/message-filtering
