### ISSUE TITLE
How would you make secure private messages with channels and current access key?

### ISSUE THREAD

**Issue by Nefiron** [emitter-io/emitter#87]
Hey developers.

I've been looking into the documentation on Emitter and I have been wondering how it could solve my usecase. Since I am not quite certain about how the channel filtering and key works I would like some advice.

I would like to use it as the broadcaster to my users, but also be able to let specific users send message to each other through a channel privately.
How would you then achieve private messaging? Basically the setup would be that a user writes a message that gets passed to NodeJS that will then act as a client, then connect to emitter and broadcast it to another user that's listening on emitter.

But how would it be secure enough so the sender and the reciever won't have other people tapping in on the line? Is there a way to dynamically make a key relationship? Or how would this be achieved if it's even possible to do such specific things?

Kind Regards.

**Comment by Florimond** [comment]
For things like this, I found that the easiest solution is generally to generate sub-channels that are GUIDs.
As per GUIDs properties, it's extremely-extremely unlikely someone is going to type a random guid and find an actual conversation.

**Comment by Nefiron** [comment]
That is also one way I have been thinking about. You would basically have the client subscribe to a channel with a unique GUID and then have a server to publish to that channel. Then of course you need to store and generate keys for this for every user.

But with the whole channel approach that emitter is using, i'm having trouble with being more specific in terms of when it's okay for someone to listen and when it's not.
