### ISSUE TITLE
Subscriber not getting every message

### ISSUE THREAD

**Issue by himadrinath** [emitter-io/emitter#9]
![emitter](https://cloud.githubusercontent.com/assets/12247490/26639984/f6e340f4-4643-11e7-862e-13e018d25d14.gif)
**WHY?**

**Comment by Florimond** [comment]
It's hard to tell without knowing a bit more about your setup.

You are apparently running an ASP server connected to Emitter. Are you rolling your own Emitter server locally, or using the sandbox?

What does the code that publish and the one that subscribe look like? Are no Javascript errors printed to the console?

**Comment by himadrinath** [comment]
@Florimond using sendbox. here is my backend and frontend
![emitter_msg_skips](https://cloud.githubusercontent.com/assets/12247490/26666581/4efa777e-46be-11e7-8e7b-d24d9fcbffd6.gif)

**Comment by Florimond** [comment]
The publish method works asynchronously. If you disconnect immediately, the message won't be sent... unless sometimes some unpredictable condition made the publication process execute faster.

**Comment by VladimirAkopyan** [comment]
That's a cool gif thou
