### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by dharan1011** [emitter-io/emitter#92]
In the docs referring to page https://github.com/emitter-io/emitter/wiki/3.-Storing-Messages there is typo in para below first code example, this might mislead.

`
In the above example the message 'Bitcoin value doubled in two months time' is stored in the Emitter broker for 10080 seconds (one week).
`
In the above para which is from the wiki
10080 **minutes** is equals to one week, not _10080 seconds_
**604800** seconds is equal to one week.

**Comment by Kelindar** [comment]
Good catch, thanks. We've migrated all of this on our website tho https://emitter.io

**Comment by dharan1011** [comment]
The same is reflected in your website. Its quite misleading. Hope changes are made.
