### ISSUE TITLE
error during subscribe received

### ISSUE THREAD

**Issue by snaquaye** [emitter-io/emitter#94]
Hello,
I've been struggling with this, since morning. When I try subscribing to a channel, using a channel key, generated from the keygen, it displaying the following in the logs

```
2018/03/19 15:27:44 [conn] created (8491AD30)
2018/03/19 15:27:45 [conn] created (8591AD30)
2018/03/19 15:27:45 [conn] error during subscribe received (The security key provided is not authorized to perform this operation.)
```

Can anyone help me out?
Thanks

**Comment by Florimond** [comment]
Could you post how you generate the key, and how do you subscribe?

**Comment by snaquaye** [comment]
I generate the key from `myipaddress:8080/keygen` and use the following code for subscription

```
const subscriptionList = [
  `${process.env.EMITTER_CHANNEL}/oauth-server/user_registered`
];

const client = emitter.connect({
    host: process.env.EMITTER_HOST,
    port: process.env.EMITTER_PORT
  }, () => {
    console.log('connected');
  });

  client.on('connect', () => {
    const uniqueSubscriptionList = new Set(subscriptionList);

    if (uniqueSubscriptionList.size) {
      uniqueSubscriptionList.forEach((subscriptionItem, index, array) => {
        client.subscribe({
          channel: subscriptionItem,
          key: process.env.EMITTER_KEY
        });
      });
    }
  });
```

**Comment by snaquaye** [comment]
I would also want to add, using the same code and a local installation of emitter, on my development machine, the client was able to subscribe to emitter seamlessly.

**Comment by Florimond** [comment]
>I generate the key from myipaddress:8080/keygen

> I would also want to add, using the same code and a local installation of emitter, on my development machine, the client was able to subscribe to emitter seamlessly.

If you generate a key locally (myipaddress:8080/keygen), this key will only be valid for your license, on your servers.

Other than that, you may want to check the documentation here at the bottom of the page : https://emitter.io/develop/message-filtering/

**Comment by snaquaye** [comment]
I'm currently using the key generated by the server on the server and not mismatching them.

Thanks

**Comment by rezam90** [comment]
Hi
I have the same issue.
I run docker then it gives me the `license` and `secret key`. I put `license` as `EMITTER_LICENSE`.
I'm using emitter-go provided example with `o.AddBroker("tcp://127.0.0.1:8080")`.

I replaced the key in `main.go` with the secret key `emitter docker` gave at first run

but it returns an error:
`error during publish received (The security key provided is not authorized to perform this operation.`
