### ISSUE TITLE
Channels and their keys

### ISSUE THREAD

**Issue by jurgen-kluft** [emitter-io/emitter#97]
Hi, is there an easy way to pre-configure all channels and their keys.
It seems currently you have to go through the key-generator page?, or maybe i missed something?

Any help is awesome...

**Comment by jurgen-kluft** [comment]
My use-case is:
* Home automation using Go
* Multiple (~12 processes) that manage different parts (calendar, hue
lighting, yee lights, xiaomi gateway, etc..)
* Using emitter.io/emitter as a pub-sub connectivity between these
processes, pushing/requesting state and configuration.

This results in having quite a number of channels:
* every process subs to its own config channel
* state/light
* sensor/motion
* sensor/switch
* sensor/flux/hue
* sensor/flux/yee
* sensor/calendar/season
* sensor/calendar/suncalc
* sensor/weather/current
* sensor/weather/hourly
* ....

So i was trying to figure out if i can setup keys for these channels from a
configuration file or where i could 'hack' into the
broker code?

Btw, i found the documentation a bit lacking, the code however is very
clean and well setup. My first small struggle was
with adding the URI of my own broker.

-Jurgen

**Comment by Florimond** [comment]
Not from a configuration file. I would simply use the keygen api.

Are you talking about the documentation about rolling your own servers?

**Comment by jurgen-kluft** [comment]
For the channel keys i am indeed now using the keygen api, so all is good
now.


As for the documentation i was indeed referring to setting up your own
server.
There are details missing in the examples when you have your own
broker/server.
Also there is no description on how to change the storage, currently it is
in-memory,
but is there a way to use a key-value store or disk?
It seems Hashicorp Vault can also be used to store secrets and keys but
there is no
documentation.

Best
Jurgen

**Comment by jurgen-kluft** [comment]
Requesting a channel key from the broker succeeds, also for the second process (the channel-keys are different). Then i proceeded to take the key from the first process and use that in the second process, still publishing a message is not received by the first process who is a subscriber. 
The 2nd process is the one that connects to the broker and does a PublishTTL.
The only thing that seems to work is if i go to the /keygen page and register manually.

Am i doing something wrong when requesting a key from the server from my process (written in Go)?

P.S.: I had to search what to fill in for the 'Type' as "rwslp" to give it all the rights.

Best
Jurgen

**Comment by jurgen-kluft** [comment]
Ok i was a bit too premature in my above statement, it does work now.
Process 1 requests a key with "rwslp" rights and subscribes to channel X.
Process 2 requests a key with "rwslp" rights and publishes a message to channel X.
Channel keys are different, but the message is received by process 1.

So it all works now!

**Comment by bagitom** [comment]
hello!

please let me know @Florimond or @jurgen-kluft, how to use securely emitter.io with javascript. Since it is a client side-script, the channel key will shown in the DOM, so it can be stolen. 
Sould I generate a new channel key in (let's say) every 10 minutes? A bit more secure, but it doesn't seem to be the correct solution.

But if I have to do it like above, then:
1) how to generate the new channel key? It must not be made on client side, in order not to be shown  my secret key in the DOM :)

2) (if it is needed,) how to tidy the zombie channels after every 10 minutes?

thanks
Tamas

**Comment by Florimond** [comment]
@bagitom 
There is the notion of extendable channels now. If I remember correctly, it should work like this...

- You create type `e` key for a root channel to give to (A). It should only be able to extend.
- You create a key with full rights to this root channel to give to (B).
- (B) subscribes to the root channel and all sub-channels.
- (A) extends his channel with his special key by calling Keygen. It receives a response with the the root channel to which was added a random suffix, this is your extension.
- (A) publishes sort of a `hello` to his extended channel, that way (B) sees a message coming from this extended channel and knows to answer through that specific channel.
