### ISSUE TITLE
Which QoS levels does emitter support?

### ISSUE THREAD

**Issue by SeppPenner** [emitter-io/emitter#98]
It would be good to have a section in the documentation that states which QoS levels emitter supports.

**Comment by Kelindar** [comment]
Currently QoS 0 only, but QoS 1 is planned. We'll add this to the documentation, good point.

**Comment by wangh09** [comment]
Is there a roadmap on supporting QoS1? cause QoS 0 is not suitable for many applications.

**Comment by Kelindar** [comment]
It is on our roadmap, contributions are welcome.
